L4DIR=/home/ijyothi/l4
OBJ_BASE=/home/ijyothi/build-zynq
OBJ_DIR=/home/ijyothi/build-zynq/pkg/libfdt/lib/build-frst
SRC_DIR=/home/ijyothi/l4/pkg/libfdt/lib/build-frst
PKGDIR=/home/ijyothi/l4/pkg/libfdt
PKGDIR_ABS=/home/ijyothi/l4/pkg/libfdt
PKGDIR_OBJ=/home/ijyothi/build-zynq/pkg/libfdt
MAKECONFLOCAL=/home/ijyothi/l4/pkg/libfdt/lib/build-frst/Makeconf.local
OSYSTEM=arm-plain
SYSTEM=arm_armv7a-std-plain
ARCH=arm
CPU=armv7a
L4API=plain
VARIANT=std
vpath %.c /home/ijyothi/l4/pkg/libfdt/lib/build-frst
vpath %.cc /home/ijyothi/l4/pkg/libfdt/lib/build-frst
vpath %.cpp /home/ijyothi/l4/pkg/libfdt/lib/build-frst
vpath %.f /home/ijyothi/l4/pkg/libfdt/lib/build-frst
vpath %.F /home/ijyothi/l4/pkg/libfdt/lib/build-frst
vpath %.f90 /home/ijyothi/l4/pkg/libfdt/lib/build-frst
vpath %.F90 /home/ijyothi/l4/pkg/libfdt/lib/build-frst
vpath %.f95 /home/ijyothi/l4/pkg/libfdt/lib/build-frst
vpath %.F95 /home/ijyothi/l4/pkg/libfdt/lib/build-frst
vpath %.S /home/ijyothi/l4/pkg/libfdt/lib/build-frst
vpath %.y /home/ijyothi/l4/pkg/libfdt/lib/build-frst
vpath %.l /home/ijyothi/l4/pkg/libfdt/lib/build-frst
vpath %.ld /home/ijyothi/l4/pkg/libfdt/lib/build-frst
vpath %.dpe /home/ijyothi/l4/pkg/libfdt/lib/build-frst
vpath %.dts /home/ijyothi/l4/pkg/libfdt/lib/build-frst
.general.d: /home/ijyothi/l4/pkg/libfdt/lib/build-frst/Makefile
include $(OBJ_BASE)/include/config/auto.conf
include /home/ijyothi/l4/pkg/libfdt/lib/build-frst/Makefile
include $(L4DIR)/mk/lib.mk
