L4DIR=/home/ijyothi/l4
OBJ_BASE=/home/ijyothi/build-zynq
OBJ_DIR=/home/ijyothi/build-zynq/pkg/l4re-core/uclibc/lib/libpthread/src
SRC_DIR=/home/ijyothi/l4/pkg/l4re-core/uclibc/lib/libpthread/src
PKGDIR=/home/ijyothi/l4/pkg/l4re-core/uclibc
PKGDIR_ABS=/home/ijyothi/l4/pkg/l4re-core/uclibc
PKGDIR_OBJ=/home/ijyothi/build-zynq/pkg/l4re-core/uclibc
MAKECONFLOCAL=/home/ijyothi/l4/pkg/l4re-core/uclibc/lib/libpthread/src/Makeconf.local
OSYSTEM=arm-l4f
SYSTEM=arm_armv7a-nofpu-l4f
ARCH=arm
CPU=armv7a
L4API=l4f
VARIANT=nofpu
vpath %.c /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/libpthread/src
vpath %.cc /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/libpthread/src
vpath %.cpp /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/libpthread/src
vpath %.f /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/libpthread/src
vpath %.F /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/libpthread/src
vpath %.f90 /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/libpthread/src
vpath %.F90 /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/libpthread/src
vpath %.f95 /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/libpthread/src
vpath %.F95 /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/libpthread/src
vpath %.S /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/libpthread/src
vpath %.y /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/libpthread/src
vpath %.l /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/libpthread/src
vpath %.ld /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/libpthread/src
vpath %.dpe /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/libpthread/src
vpath %.dts /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/libpthread/src
.general.d: /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/libpthread/src/Makefile
include $(OBJ_BASE)/include/config/auto.conf
include /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/libpthread/src/Makefile
include $(L4DIR)/mk/lib.mk
