savedcmd_c++11/cow-sstream-inst.o := /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/bin/arm-none-linux-gnueabihf-g++ -c -MD -MP -MF c++11/.cow-sstream-inst.o.d -DL4SYS_USE_UTCB_WRAP=1 -DL4_MINIMAL_LIBC -Dlinux -DSYSTEM_arm_armv7a_std_l4f -DARCH_arm -DCPUTYPE_armv7a -DL4API_l4f -D_GNU_SOURCE -march=armv7-a+fp -I/home/ijyothi/l4/pkg/l4re-core/libstdc++-v3-minimal/../libstdc++-v3/private_inc -I/home/ijyothi/build-zynq/include/contrib/libgcc_eh -I/home/ijyothi/build-zynq/include/contrib/libstdc++-v3 -I/home/ijyothi/build-zynq/include/arm/l4f -I/home/ijyothi/build-zynq/include/arm -I/home/ijyothi/build-zynq/include -I/home/ijyothi/build-zynq/include/contrib/libstdc++-v3 -nostdinc -I/home/ijyothi/build-zynq/include/uclibc -isystem /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/bin/../lib/gcc/arm-none-linux-gnueabihf/12.3.1/include -isystem /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/bin/../lib/gcc/arm-none-linux-gnueabihf/12.3.1/include-fixed -std=gnu++11 -fno-omit-frame-pointer -fno-unwind-tables -g -O2 -fno-strict-aliasing -Wextra -Wdouble-promotion -Wfloat-conversion -Wfloat-equal -Wlogical-op -Wall -Wmissing-declarations -Wno-missing-declarations -Wno-float-equal -Wno-unused-parameter -Wno-noexcept-type -Wno-psabi -fno-common -march=armv7-a+fp -marm -fmacro-prefix-map=/home/ijyothi/l4/= -fmacro-prefix-map=/home/ijyothi/build-zynq/= -DL4_GCC_HAS_ATOMICS -fno-stack-protector -fuse-cxa-atexit -ffunction-sections -fdata-sections /home/ijyothi/l4/pkg/l4re-core/libstdc++-v3-minimal/../libstdc++-v3/contrib/libstdc++-v3-12/src/c++11/cow-sstream-inst.cc -o c++11/cow-sstream-inst.o

source_c++11/cow-sstream-inst.o := /home/ijyothi/l4/pkg/l4re-core/libstdc++-v3-minimal/../libstdc++-v3/contrib/libstdc++-v3-12/src/c++11/cow-sstream-inst.cc

deps_c++11/cow-sstream-inst.o := \
  /home/ijyothi/l4/pkg/l4re-core/libstdc++-v3-minimal/../libstdc++-v3/contrib/libstdc++-v3-12/src/c++11/sstream-inst.cc \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/sstream \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/istream \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/ios \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/iosfwd \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/c++config.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/os_defines.h \
  /home/ijyothi/build-zynq/include/uclibc/features.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/uClibc_config.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/l4-libc-symbols.h \
  /home/ijyothi/build-zynq/include/uclibc/sys/cdefs.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/cpu_defines.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/stringfwd.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/memoryfwd.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/postypes.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/cwchar \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/exception \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/exception.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/exception_ptr.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/exception_defines.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/cxxabi_init_exception.h \
  /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/lib/gcc/arm-none-linux-gnueabihf/12.3.1/include/stddef.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/typeinfo \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/hash_bytes.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/new \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/move.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/type_traits \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/nested_exception.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/char_traits.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/cstdint \
  /home/ijyothi/build-zynq/include/uclibc/stdint.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/wordsize.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/localefwd.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/c++locale.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/clocale \
  /home/ijyothi/build-zynq/include/uclibc/locale.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/uClibc_locale.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/cctype \
  /home/ijyothi/build-zynq/include/uclibc/ctype.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/types.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/typesizes.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/uClibc_touplow.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/ios_base.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/ext/atomicity.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/gthr.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/gthr-single.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/atomic_word.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/locale_classes.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/string \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/allocator.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/c++allocator.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/new_allocator.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/functexcept.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/cpp_type_traits.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/ostream_insert.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/cxxabi_forced.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/stl_iterator_base_types.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/stl_iterator_base_funcs.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/concept_check.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/debug/assertions.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/stl_iterator.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/ext/type_traits.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/ptr_traits.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/stl_function.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/backward/binders.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/ext/numeric_traits.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/stl_algobase.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/stl_pair.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/utility.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/debug/debug.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/predefined_ops.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/refwrap.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/invoke.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/range_access.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/initializer_list \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/basic_string.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/ext/alloc_traits.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/alloc_traits.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/stl_construct.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/cow_string.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/ext/string_conversions.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/cstdlib \
  /home/ijyothi/build-zynq/include/uclibc/stdlib.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/waitflags.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/waitstatus.h \
  /home/ijyothi/build-zynq/include/uclibc/endian.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/endian.h \
  /home/ijyothi/build-zynq/include/uclibc/byteswap.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/byteswap.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/byteswap-common.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/byteswap-16.h \
  /home/ijyothi/build-zynq/include/uclibc/sys/types.h \
  /home/ijyothi/build-zynq/include/uclibc/time.h \
  /home/ijyothi/build-zynq/include/uclibc/sys/select.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/select.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/sigset.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/time.h \
  /home/ijyothi/build-zynq/include/uclibc/sys/sysmacros.h \
  /home/ijyothi/build-zynq/include/uclibc/alloca.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/std_abs.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/cstdio \
  /home/ijyothi/build-zynq/include/uclibc/stdio.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/uClibc_stdio.h \
  /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/lib/gcc/arm-none-linux-gnueabihf/12.3.1/include/stdarg.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/stdio_lim.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/cerrno \
  /home/ijyothi/build-zynq/include/uclibc/errno.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/errno.h \
  /home/ijyothi/build-zynq/include/uclibc/linux/errno.h \
  /home/ijyothi/build-zynq/include/uclibc/asm/errno.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/charconv.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/functional_hash.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/basic_string.tcc \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/locale_classes.tcc \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/system_error \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/error_constants.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/stdexcept \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/streambuf \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/streambuf.tcc \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/basic_ios.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/locale_facets.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/cwctype \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/ctype_base.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/streambuf_iterator.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/ctype_inline.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/locale_facets.tcc \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/basic_ios.tcc \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/ostream \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/ostream.tcc \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/istream.tcc \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/sstream.tcc \

c++11/cow-sstream-inst.o: $(deps_c++11/cow-sstream-inst.o)

$(deps_c++11/cow-sstream-inst.o):
