L4DIR=/home/ijyothi/l4
OBJ_BASE=/home/ijyothi/build-zynq
OBJ_DIR=/home/ijyothi/build-zynq/pkg/l4re-core/libstdc++-v3-minimal
SRC_DIR=/home/ijyothi/l4/pkg/l4re-core/libstdc++-v3-minimal
PKGDIR=/home/ijyothi/l4/pkg/l4re-core/libstdc++-v3-minimal
PKGDIR_ABS=/home/ijyothi/l4/pkg/l4re-core/libstdc++-v3-minimal
PKGDIR_OBJ=/home/ijyothi/build-zynq/pkg/l4re-core/libstdc++-v3-minimal
MAKECONFLOCAL=/home/ijyothi/l4/pkg/l4re-core/libstdc++-v3-minimal/Makeconf.local
OSYSTEM=arm-l4f
SYSTEM=arm_armv7a-std-l4f
ARCH=arm
CPU=armv7a
L4API=l4f
VARIANT=std
vpath %.c /home/ijyothi/l4/pkg/l4re-core/libstdc++-v3-minimal
vpath %.cc /home/ijyothi/l4/pkg/l4re-core/libstdc++-v3-minimal
vpath %.cpp /home/ijyothi/l4/pkg/l4re-core/libstdc++-v3-minimal
vpath %.f /home/ijyothi/l4/pkg/l4re-core/libstdc++-v3-minimal
vpath %.F /home/ijyothi/l4/pkg/l4re-core/libstdc++-v3-minimal
vpath %.f90 /home/ijyothi/l4/pkg/l4re-core/libstdc++-v3-minimal
vpath %.F90 /home/ijyothi/l4/pkg/l4re-core/libstdc++-v3-minimal
vpath %.f95 /home/ijyothi/l4/pkg/l4re-core/libstdc++-v3-minimal
vpath %.F95 /home/ijyothi/l4/pkg/l4re-core/libstdc++-v3-minimal
vpath %.S /home/ijyothi/l4/pkg/l4re-core/libstdc++-v3-minimal
vpath %.y /home/ijyothi/l4/pkg/l4re-core/libstdc++-v3-minimal
vpath %.l /home/ijyothi/l4/pkg/l4re-core/libstdc++-v3-minimal
vpath %.ld /home/ijyothi/l4/pkg/l4re-core/libstdc++-v3-minimal
vpath %.dpe /home/ijyothi/l4/pkg/l4re-core/libstdc++-v3-minimal
vpath %.dts /home/ijyothi/l4/pkg/l4re-core/libstdc++-v3-minimal
.general.d: /home/ijyothi/l4/pkg/l4re-core/libstdc++-v3-minimal/Makefile
include $(OBJ_BASE)/include/config/auto.conf
include /home/ijyothi/l4/pkg/l4re-core/libstdc++-v3-minimal/Makefile
include $(L4DIR)/mk/lib.mk
