L4DIR=/home/ijyothi/l4
OBJ_BASE=/home/ijyothi/build-zynq
OBJ_DIR=/home/ijyothi/build-zynq/pkg/l4re-core/uclibc/lib/uclibc
SRC_DIR=/home/ijyothi/l4/pkg/l4re-core/uclibc/lib/uclibc
PKGDIR=/home/ijyothi/l4/pkg/l4re-core/uclibc
PKGDIR_ABS=/home/ijyothi/l4/pkg/l4re-core/uclibc
PKGDIR_OBJ=/home/ijyothi/build-zynq/pkg/l4re-core/uclibc
MAKECONFLOCAL=/home/ijyothi/l4/pkg/l4re-core/uclibc/lib/uclibc/Makeconf.local
OSYSTEM=arm-l4f
SYSTEM=arm_armv7a-nofpu-l4f
ARCH=arm
CPU=armv7a
L4API=l4f
VARIANT=nofpu
vpath %.c /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/uclibc
vpath %.cc /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/uclibc
vpath %.cpp /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/uclibc
vpath %.f /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/uclibc
vpath %.F /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/uclibc
vpath %.f90 /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/uclibc
vpath %.F90 /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/uclibc
vpath %.f95 /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/uclibc
vpath %.F95 /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/uclibc
vpath %.S /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/uclibc
vpath %.y /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/uclibc
vpath %.l /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/uclibc
vpath %.ld /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/uclibc
vpath %.dpe /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/uclibc
vpath %.dts /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/uclibc
.general.d: /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/uclibc/Make.rules
include $(OBJ_BASE)/include/config/auto.conf
include /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/uclibc/Make.rules
include $(L4DIR)/mk/lib.mk
