savedcmd_vm.o := /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/bin/arm-none-linux-gnueabihf-g++ -c -MD -MP -MF ./.vm.o.d -DSYSTEM_arm_armv7a_nofpu_l4f -DARCH_arm -DCPUTYPE_armv7a -DL4API_l4f -D_GNU_SOURCE -DBID_VARIANT_FLAG_NOFPU -mgeneral-regs-only -march=armv7ve+fp -I/home/ijyothi/l4/pkg/uvmm/server/src/../include -I/home/ijyothi/l4/pkg/uvmm/server/src -I/home/ijyothi/l4/pkg/uvmm/server/src/ARCH-arm -I/home/ijyothi/l4/pkg/uvmm/server/src/../../tools/uvmm_cli -I/home/ijyothi/l4/pkg/uvmm/server/src/arm -I/home/ijyothi/l4/pkg/uvmm/server/src/device/arm -I/home/ijyothi/build-zynq/include/contrib/libfdt -I/home/ijyothi/build-zynq/include/contrib/libstdc++-v3 -I/home/ijyothi/build-zynq/include/contrib/libgcc_eh -I/home/ijyothi/build-zynq/include/contrib/zlib -I/home/ijyothi/build-zynq/include/arm/l4f -I/home/ijyothi/build-zynq/include/arm -I/home/ijyothi/build-zynq/include -I/home/ijyothi/build-zynq/include/contrib/libstdc++-v3 -nostdinc -I/home/ijyothi/build-zynq/include/uclibc -isystem /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/bin/../lib/gcc/arm-none-linux-gnueabihf/12.3.1/include -isystem /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/bin/../lib/gcc/arm-none-linux-gnueabihf/12.3.1/include-fixed -fno-omit-frame-pointer -fno-unwind-tables -g -O3 -Wextra -Wdouble-promotion -Wfloat-conversion -Wfloat-equal -Wlogical-op -Wall -Wmissing-declarations -Wno-noexcept-type -Wno-psabi -fno-common -mgeneral-regs-only -march=armv7ve+fp -marm -fmacro-prefix-map=/home/ijyothi/l4/= -fmacro-prefix-map=/home/ijyothi/build-zynq/= -DL4_GCC_HAS_ATOMICS -fstack-protector -fuse-cxa-atexit -ffunction-sections -fdata-sections /home/ijyothi/l4/pkg/uvmm/server/src/vm.cc -o vm.o

source_vm.o := /home/ijyothi/l4/pkg/uvmm/server/src/vm.cc

deps_vm.o := \
  /home/ijyothi/l4/pkg/uvmm/server/src/vm.h \
  /home/ijyothi/l4/pkg/uvmm/server/src/cpu_dev_array.h \
  /home/ijyothi/build-zynq/include/l4/re/env \
  /home/ijyothi/build-zynq/include/l4/sys/types.h \
  /home/ijyothi/build-zynq/include/arm/l4/sys/l4int.h \
  /home/ijyothi/build-zynq/include/l4/sys/l4int.h \
  /home/ijyothi/build-zynq/include/l4/sys/compiler.h \
  /home/ijyothi/build-zynq/include/arm/l4/sys/linkage.h \
  /home/ijyothi/build-zynq/include/arm/l4/sys/consts.h \
  /home/ijyothi/build-zynq/include/l4/sys/consts.h \
  /home/ijyothi/build-zynq/include/l4/sys/__l4_fpage.h \
  /home/ijyothi/build-zynq/include/l4/sys/__timeout.h \
  /home/ijyothi/build-zynq/include/l4/re/rm \
  /home/ijyothi/build-zynq/include/l4/sys/capability \
  /home/ijyothi/build-zynq/include/l4/sys/kobject \
  /home/ijyothi/build-zynq/include/l4/sys/kernel_object.h \
  /home/ijyothi/build-zynq/include/arm/l4/sys/utcb.h \
  /home/ijyothi/build-zynq/include/l4/sys/utcb.h \
  /home/ijyothi/build-zynq/include/l4/sys/__kernel_object_impl.h \
  /home/ijyothi/build-zynq/include/arm/l4f/l4/sys/ipc.h \
  /home/ijyothi/build-zynq/include/l4/sys/ipc.h \
  /home/ijyothi/build-zynq/include/l4/sys/err.h \
  /home/ijyothi/build-zynq/include/arm/l4f/l4/sys/syscall_defs.h \
  /home/ijyothi/build-zynq/include/l4/sys/__typeinfo.h \
  /home/ijyothi/build-zynq/include/l4/sys/cxx/types \
  /home/ijyothi/build-zynq/include/l4/sys/cxx/ipc_basics \
  /home/ijyothi/build-zynq/include/l4/sys/cxx/capability.h \
  /home/ijyothi/build-zynq/include/arm/l4/sys/task.h \
  /home/ijyothi/build-zynq/include/l4/sys/task.h \
  /home/ijyothi/build-zynq/include/l4/sys/__task-arm.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/typeinfo \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/exception.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/c++config.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/os_defines.h \
  /home/ijyothi/build-zynq/include/uclibc/features.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/uClibc_config.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/l4-libc-symbols.h \
  /home/ijyothi/build-zynq/include/uclibc/sys/cdefs.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/cpu_defines.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/pstl/pstl_config.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/hash_bytes.h \
  /home/ijyothi/build-zynq/include/l4/sys/meta \
  /home/ijyothi/build-zynq/include/l4/sys/cxx/ipc_iface \
  /home/ijyothi/build-zynq/include/l4/sys/cxx/ipc_types \
    $(wildcard include/config/ALLOW_REFS) \
  /home/ijyothi/build-zynq/include/l4/sys/cxx/ipc_string \
  /home/ijyothi/build-zynq/include/l4/sys/cxx/ipc_array \
  /home/ijyothi/build-zynq/include/l4/re/protocols.h \
  /home/ijyothi/build-zynq/include/l4/sys/pager \
  /home/ijyothi/build-zynq/include/l4/sys/cxx/ipc_ret_array \
  /home/ijyothi/build-zynq/include/l4/re/consts \
  /home/ijyothi/build-zynq/include/l4/re/env.h \
  /home/ijyothi/build-zynq/include/l4/sys/kip.h \
    $(wildcard include/config/SYNC_TSC) \
    $(wildcard include/config/SYNC) \
  /home/ijyothi/build-zynq/include/arm/l4/sys/__kip-arch.h \
  /home/ijyothi/build-zynq/include/l4/sys/__kip-32bit.h \
  /home/ijyothi/build-zynq/include/l4/re/consts.h \
  /home/ijyothi/build-zynq/include/l4/re/dataspace \
  /home/ijyothi/build-zynq/include/l4/re/parent \
  /home/ijyothi/build-zynq/include/l4/re/mem_alloc \
  /home/ijyothi/build-zynq/include/l4/sys/factory \
  /home/ijyothi/build-zynq/include/l4/sys/factory.h \
  /home/ijyothi/build-zynq/include/l4/sys/cxx/ipc_varg \
  /home/ijyothi/build-zynq/include/l4/re/log \
  /home/ijyothi/build-zynq/include/l4/sys/vcon \
  /home/ijyothi/build-zynq/include/l4/sys/icu \
  /home/ijyothi/build-zynq/include/l4/sys/irq \
  /home/ijyothi/build-zynq/include/l4/sys/icu.h \
  /home/ijyothi/build-zynq/include/l4/sys/irq.h \
  /home/ijyothi/build-zynq/include/l4/sys/rcv_endpoint.h \
  /home/ijyothi/build-zynq/include/l4/sys/rcv_endpoint \
  /home/ijyothi/build-zynq/include/l4/sys/vcon.h \
  /home/ijyothi/build-zynq/include/l4/sys/scheduler \
  /home/ijyothi/build-zynq/include/l4/sys/scheduler.h \
  /home/ijyothi/l4/pkg/uvmm/server/src/debug.h \
  /home/ijyothi/build-zynq/include/l4/re/util/debug \
  /home/ijyothi/l4/pkg/uvmm/server/src/device.h \
  /home/ijyothi/build-zynq/include/l4/cxx/ref_ptr \
  /home/ijyothi/build-zynq/include/l4/cxx/type_traits \
  /home/ijyothi/build-zynq/include/l4/cxx/bits/type_traits.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/cstddef \
  /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/lib/gcc/arm-none-linux-gnueabihf/12.3.1/include/stddef.h \
  /home/ijyothi/build-zynq/include/l4/cxx/exceptions \
  /home/ijyothi/build-zynq/include/l4/cxx/l4types.h \
  /home/ijyothi/build-zynq/include/l4/cxx/basic_ostream \
  /home/ijyothi/build-zynq/include/l4/util/backtrace.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/string \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/stringfwd.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/memoryfwd.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/char_traits.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/postypes.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/cwchar \
  /home/ijyothi/build-zynq/include/uclibc/wchar.h \
  /home/ijyothi/build-zynq/include/uclibc/stdio.h \
  /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/lib/gcc/arm-none-linux-gnueabihf/12.3.1/include/stdarg.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/wchar.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/type_traits \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/cstdint \
  /home/ijyothi/build-zynq/include/uclibc/stdint.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/wordsize.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/allocator.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/c++allocator.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/new_allocator.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/new \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/functexcept.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/exception_defines.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/move.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/cpp_type_traits.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/localefwd.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/c++locale.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/clocale \
  /home/ijyothi/build-zynq/include/uclibc/locale.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/uClibc_locale.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/iosfwd \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/cctype \
  /home/ijyothi/build-zynq/include/uclibc/ctype.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/types.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/typesizes.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/uClibc_touplow.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/ostream_insert.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/cxxabi_forced.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/stl_iterator_base_types.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/stl_iterator_base_funcs.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/concept_check.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/debug/assertions.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/stl_iterator.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/ext/type_traits.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/ptr_traits.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/stl_function.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/backward/binders.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/ext/numeric_traits.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/stl_algobase.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/stl_pair.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/utility.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/debug/debug.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/predefined_ops.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/refwrap.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/invoke.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/range_access.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/initializer_list \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/basic_string.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/ext/alloc_traits.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/alloc_traits.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/stl_construct.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/string_view \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/functional_hash.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/string_view.tcc \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/ext/string_conversions.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/cstdlib \
  /home/ijyothi/build-zynq/include/uclibc/stdlib.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/waitflags.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/waitstatus.h \
  /home/ijyothi/build-zynq/include/uclibc/endian.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/endian.h \
  /home/ijyothi/build-zynq/include/uclibc/byteswap.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/byteswap.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/byteswap-common.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/byteswap-16.h \
  /home/ijyothi/build-zynq/include/uclibc/sys/types.h \
  /home/ijyothi/build-zynq/include/uclibc/time.h \
  /home/ijyothi/build-zynq/include/uclibc/sys/select.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/select.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/sigset.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/time.h \
  /home/ijyothi/build-zynq/include/uclibc/sys/sysmacros.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/pthreadtypes.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/sched.h \
  /home/ijyothi/build-zynq/include/uclibc/alloca.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/std_abs.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/cstdio \
  /home/ijyothi/build-zynq/include/uclibc/bits/uClibc_stdio.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/stdio_lim.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/cerrno \
  /home/ijyothi/build-zynq/include/uclibc/errno.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/errno.h \
  /home/ijyothi/build-zynq/include/uclibc/linux/errno.h \
  /home/ijyothi/build-zynq/include/uclibc/asm/errno.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/charconv.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/basic_string.tcc \
  /home/ijyothi/l4/pkg/uvmm/server/src/../include/device_tree.h \
  /home/ijyothi/build-zynq/include/l4/re/error_helper \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/utility \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/stl_relops.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/map \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/stl_tree.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/ext/aligned_buffer.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/node_handle.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/stl_map.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/tuple \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/uses_allocator.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/stl_multimap.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/erase_if.h \
  /home/ijyothi/build-zynq/include/contrib/libfdt/libfdt.h \
  /home/ijyothi/build-zynq/include/contrib/libfdt/libfdt_env.h \
  /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/lib/gcc/arm-none-linux-gnueabihf/12.3.1/include/stdbool.h \
  /home/ijyothi/build-zynq/include/uclibc/string.h \
  /home/ijyothi/build-zynq/include/uclibc/limits.h \
  /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/lib/gcc/arm-none-linux-gnueabihf/12.3.1/include-fixed/limits.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/posix1_lim.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/local_lim.h \
  /home/ijyothi/build-zynq/include/uclibc/linux/limits.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/uClibc_local_lim.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/posix2_lim.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/xopen_lim.h \
  /home/ijyothi/build-zynq/include/contrib/libfdt/fdt.h \
  /home/ijyothi/l4/pkg/uvmm/server/src/../include/cell.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/cassert \
  /home/ijyothi/build-zynq/include/uclibc/assert.h \
  /home/ijyothi/l4/pkg/uvmm/server/src/arm/cpu_dev.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/atomic \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/atomic_base.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/atomic_lockfree_defines.h \
  /home/ijyothi/l4/pkg/uvmm/server/src/generic_cpu_dev.h \
  /home/ijyothi/build-zynq/include/uclibc/pthread.h \
  /home/ijyothi/build-zynq/include/uclibc/sched.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/uClibc_clk_tck.h \
  /home/ijyothi/build-zynq/include/uclibc/signal.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/initspin.h \
  /home/ijyothi/build-zynq/include/uclibc/pthread-l4.h \
  /home/ijyothi/build-zynq/include/l4/sys/thread \
  /home/ijyothi/build-zynq/include/arm/l4/sys/thread.h \
  /home/ijyothi/build-zynq/include/l4/sys/thread.h \
  /home/ijyothi/build-zynq/include/l4/cxx/unique_ptr \
  /home/ijyothi/build-zynq/include/l4/re/util/kumem_alloc \
  /home/ijyothi/build-zynq/include/l4/re/util/br_manager \
  /home/ijyothi/build-zynq/include/l4/re/util/cap_alloc \
  /home/ijyothi/build-zynq/include/l4/re/util/cap_alloc_impl.h \
  /home/ijyothi/build-zynq/include/l4/re/util/counting_cap_alloc \
  /home/ijyothi/build-zynq/include/l4/sys/task \
  /home/ijyothi/build-zynq/include/l4/sys/assert.h \
  /home/ijyothi/build-zynq/include/l4/sys/smart_capability \
  /home/ijyothi/build-zynq/include/l4/sys/cxx/ipc_server_loop \
  /home/ijyothi/build-zynq/include/l4/sys/cxx/ipc_epiface \
  /home/ijyothi/build-zynq/include/l4/sys/cxx/ipc_server \
  /home/ijyothi/build-zynq/include/l4/cxx/ipc_timeout_queue \
  /home/ijyothi/build-zynq/include/l4/cxx/hlist \
  /home/ijyothi/build-zynq/include/l4/cxx/bits/list_basics.h \
  /home/ijyothi/l4/pkg/uvmm/server/src/ARCH-arm/vcpu_ptr.h \
  /home/ijyothi/l4/pkg/uvmm/server/src/ARCH-arm/aarch32_hyp.h \
  /home/ijyothi/l4/pkg/uvmm/server/src/arm/arm_hyp.h \
  /home/ijyothi/build-zynq/include/l4/sys/vcpu.h \
  /home/ijyothi/build-zynq/include/arm/l4/sys/__vcpu-arch.h \
  /home/ijyothi/build-zynq/include/l4/sys/__vcpu-arm.h \
  /home/ijyothi/build-zynq/include/l4/cxx/bitfield \
  /home/ijyothi/build-zynq/include/l4/cxx/type_list \
  /home/ijyothi/l4/pkg/uvmm/server/src/generic_vcpu_ptr.h \
  /home/ijyothi/l4/pkg/uvmm/server/src/vcpu_obj_registry.h \
  /home/ijyothi/build-zynq/include/l4/re/util/object_registry \
  /home/ijyothi/build-zynq/include/l4/re/util/unique_cap \
  /home/ijyothi/build-zynq/include/l4/sys/cxx/smart_capability_1x \
  /home/ijyothi/build-zynq/include/l4/sys/ipc_gate \
  /home/ijyothi/build-zynq/include/l4/sys/ipc_gate.h \
  /home/ijyothi/l4/pkg/uvmm/server/src/mem_access.h \
  /home/ijyothi/l4/pkg/uvmm/server/src/ARCH-arm/monitor/cpu_dev_cmd_handler.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/cstring \
  /home/ijyothi/l4/pkg/uvmm/server/src/monitor/monitor.h \
    $(wildcard include/config/UVMM_MONITOR) \
    $(wildcard include/config/BUILD_ARCH_amd64) \
    $(wildcard include/config/RELEASE_MODE) \
  /home/ijyothi/build-zynq/include/l4/bid_config.h \
  /home/ijyothi/l4/pkg/uvmm/server/src/monitor/monitor_args.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/climits \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/limits \
  /home/ijyothi/l4/pkg/uvmm/server/src/monitor/cpu_dev_array_cmd_handler.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/vector \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/stl_uninitialized.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/stl_vector.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/stl_bvector.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/vector.tcc \
  /home/ijyothi/l4/pkg/uvmm/server/src/device_repo.h \
  /home/ijyothi/l4/pkg/uvmm/server/src/arm/guest.h \
  /home/ijyothi/build-zynq/include/arm/l4/sys/vm \
  /home/ijyothi/build-zynq/include/l4/sys/__vm-arm.h \
  /home/ijyothi/l4/pkg/uvmm/server/src/arm/core_timer.h \
  /home/ijyothi/l4/pkg/uvmm/server/src/irq.h \
  /home/ijyothi/build-zynq/include/l4/cxx/ipc_server \
  /home/ijyothi/build-zynq/include/l4/sys/typeinfo_svr \
  /home/ijyothi/build-zynq/include/l4/cxx/ipc_stream \
  /home/ijyothi/build-zynq/include/l4/cxx/minmax \
  /home/ijyothi/l4/pkg/uvmm/server/src/generic_guest.h \
  /home/ijyothi/build-zynq/include/l4/re/video/goos \
  /home/ijyothi/build-zynq/include/l4/re/video/colors \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/mutex \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/exception \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/exception_ptr.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/cxxabi_init_exception.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/nested_exception.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/system_error \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/error_constants.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/stdexcept \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/std_mutex.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/gthr.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/gthr-default.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/unique_lock.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/ext/atomicity.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/atomic_word.h \
  /home/ijyothi/l4/pkg/uvmm/server/src/ds_mmio_mapper.h \
  /home/ijyothi/build-zynq/include/l4/util/util.h \
  /home/ijyothi/l4/pkg/uvmm/server/src/mmio_device.h \
  /home/ijyothi/l4/pkg/uvmm/server/src/mem_types.h \
  /home/ijyothi/l4/pkg/uvmm/server/src/consts.h \
  /home/ijyothi/l4/pkg/uvmm/server/src/ds_manager.h \
  /home/ijyothi/l4/pkg/uvmm/server/src/ram_ds.h \
  /home/ijyothi/build-zynq/include/l4/re/dma_space \
  /home/ijyothi/build-zynq/include/l4/l4virtio/virtqueue \
  /home/ijyothi/l4/pkg/uvmm/server/src/address_space_manager.h \
  /home/ijyothi/l4/pkg/uvmm/server/src/virt_bus.h \
  /home/ijyothi/build-zynq/include/l4/cxx/bitmap \
  /home/ijyothi/build-zynq/include/l4/vbus/vbus \
  /home/ijyothi/build-zynq/include/l4/vbus/vbus.h \
  /home/ijyothi/build-zynq/include/l4/vbus/vbus_types.h \
  /home/ijyothi/build-zynq/include/l4/vbus/vbus_pm.h \
  /home/ijyothi/build-zynq/include/l4/re/event \
  /home/ijyothi/build-zynq/include/l4/re/event.h \
  /home/ijyothi/build-zynq/include/l4/re/inhibitor \
  /home/ijyothi/l4/pkg/uvmm/server/src/vbus_event.h \
  /home/ijyothi/build-zynq/include/l4/re/util/event \
  /home/ijyothi/build-zynq/include/l4/re/cap_alloc \
  /home/ijyothi/build-zynq/include/l4/re/util/event_buffer \
  /home/ijyothi/build-zynq/include/l4/re/event-sys.h \
  /home/ijyothi/l4/pkg/uvmm/server/src/msi_allocator.h \
  /home/ijyothi/l4/pkg/uvmm/server/src/vm_memmap.h \
  /home/ijyothi/l4/pkg/uvmm/server/src/pm.h \
  /home/ijyothi/build-zynq/include/l4/sys/platform_control \
  /home/ijyothi/build-zynq/include/l4/sys/platform_control.h \
  /home/ijyothi/l4/pkg/uvmm/server/src/io_device.h \
  /home/ijyothi/l4/pkg/uvmm/server/src/arm/gic_iface.h \
  /home/ijyothi/l4/pkg/uvmm/server/src/vm_ram.h \
  /home/ijyothi/l4/pkg/uvmm/server/src/host_dt.h \
  /home/ijyothi/l4/pkg/uvmm/server/src/monitor/dt_cmd_handler.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/algorithm \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/stl_algo.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/algorithmfwd.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/stl_heap.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/stl_tempbuf.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/uniform_int_dist.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/pstl/glue_algorithm_defs.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/pstl/execution_defs.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/stack \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/deque \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/stl_deque.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/deque.tcc \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/stl_stack.h \
  /home/ijyothi/l4/pkg/uvmm/server/src/monitor/vm_ram_cmd_handler.h \
  /home/ijyothi/l4/pkg/uvmm/server/src/monitor/mem_dump.h \
  /home/ijyothi/l4/pkg/uvmm/server/src/device/arm/smccc_device.h \
  /home/ijyothi/l4/pkg/uvmm/server/src/arm/sys_reg.h \
  /home/ijyothi/l4/pkg/uvmm/server/src/vmprint.h \
  /home/ijyothi/l4/pkg/uvmm/server/src/monitor/vm_cmd_handler.h \
  /home/ijyothi/l4/pkg/uvmm/server/src/arm/monitor/monitor_arch.h \
  /home/ijyothi/l4/pkg/uvmm/server/src/device_factory.h \
  /home/ijyothi/l4/pkg/uvmm/server/src/io_proxy.h \
  /home/ijyothi/l4/pkg/uvmm/server/src/irq_svr.h \
  /home/ijyothi/l4/pkg/uvmm/server/src/msi_controller.h \
  /home/ijyothi/l4/pkg/uvmm/server/src/pci_device.h \
  /home/ijyothi/build-zynq/include/l4/cxx/static_vector \
  /home/ijyothi/l4/pkg/uvmm/server/src/msix.h \

vm.o: $(deps_vm.o)

$(deps_vm.o):
