L4DIR=/home/ijyothi/l4
OBJ_BASE=/home/ijyothi/build-zynq
OBJ_DIR=/home/ijyothi/build-zynq/pkg/l4re-core/libc_backends/lib/minimal_io
SRC_DIR=/home/ijyothi/l4/pkg/l4re-core/libc_backends/lib/minimal_io
PKGDIR=/home/ijyothi/l4/pkg/l4re-core/libc_backends
PKGDIR_ABS=/home/ijyothi/l4/pkg/l4re-core/libc_backends
PKGDIR_OBJ=/home/ijyothi/build-zynq/pkg/l4re-core/libc_backends
MAKECONFLOCAL=/home/ijyothi/l4/pkg/l4re-core/libc_backends/lib/minimal_io/Makeconf.local
OSYSTEM=arm-l4f
SYSTEM=arm_armv7a-std-l4f
ARCH=arm
CPU=armv7a
L4API=l4f
VARIANT=std
vpath %.c /home/ijyothi/l4/pkg/l4re-core/libc_backends/lib/minimal_io
vpath %.cc /home/ijyothi/l4/pkg/l4re-core/libc_backends/lib/minimal_io
vpath %.cpp /home/ijyothi/l4/pkg/l4re-core/libc_backends/lib/minimal_io
vpath %.f /home/ijyothi/l4/pkg/l4re-core/libc_backends/lib/minimal_io
vpath %.F /home/ijyothi/l4/pkg/l4re-core/libc_backends/lib/minimal_io
vpath %.f90 /home/ijyothi/l4/pkg/l4re-core/libc_backends/lib/minimal_io
vpath %.F90 /home/ijyothi/l4/pkg/l4re-core/libc_backends/lib/minimal_io
vpath %.f95 /home/ijyothi/l4/pkg/l4re-core/libc_backends/lib/minimal_io
vpath %.F95 /home/ijyothi/l4/pkg/l4re-core/libc_backends/lib/minimal_io
vpath %.S /home/ijyothi/l4/pkg/l4re-core/libc_backends/lib/minimal_io
vpath %.y /home/ijyothi/l4/pkg/l4re-core/libc_backends/lib/minimal_io
vpath %.l /home/ijyothi/l4/pkg/l4re-core/libc_backends/lib/minimal_io
vpath %.ld /home/ijyothi/l4/pkg/l4re-core/libc_backends/lib/minimal_io
vpath %.dpe /home/ijyothi/l4/pkg/l4re-core/libc_backends/lib/minimal_io
vpath %.dts /home/ijyothi/l4/pkg/l4re-core/libc_backends/lib/minimal_io
.general.d: /home/ijyothi/l4/pkg/l4re-core/libc_backends/lib/minimal_io/Makefile
include $(OBJ_BASE)/include/config/auto.conf
include /home/ijyothi/l4/pkg/l4re-core/libc_backends/lib/minimal_io/Makefile
include $(L4DIR)/mk/lib.mk
