L4DIR=/home/ijyothi/l4
OBJ_BASE=/home/ijyothi/build-zynq
OBJ_DIR=/home/ijyothi/build-zynq/pkg/virtio-net/server/p2p-link
SRC_DIR=/home/ijyothi/l4/pkg/virtio-net/server/p2p-link
PKGDIR=/home/ijyothi/l4/pkg/virtio-net
PKGDIR_ABS=/home/ijyothi/l4/pkg/virtio-net
PKGDIR_OBJ=/home/ijyothi/build-zynq/pkg/virtio-net
MAKECONFLOCAL=/home/ijyothi/l4/pkg/virtio-net/server/p2p-link/Makeconf.local
OSYSTEM=arm-l4f
SYSTEM=arm_armv7a-std-l4f
ARCH=arm
CPU=armv7a
L4API=l4f
VARIANT=std
vpath %.c /home/ijyothi/l4/pkg/virtio-net/server/p2p-link
vpath %.cc /home/ijyothi/l4/pkg/virtio-net/server/p2p-link
vpath %.cpp /home/ijyothi/l4/pkg/virtio-net/server/p2p-link
vpath %.f /home/ijyothi/l4/pkg/virtio-net/server/p2p-link
vpath %.F /home/ijyothi/l4/pkg/virtio-net/server/p2p-link
vpath %.f90 /home/ijyothi/l4/pkg/virtio-net/server/p2p-link
vpath %.F90 /home/ijyothi/l4/pkg/virtio-net/server/p2p-link
vpath %.f95 /home/ijyothi/l4/pkg/virtio-net/server/p2p-link
vpath %.F95 /home/ijyothi/l4/pkg/virtio-net/server/p2p-link
vpath %.S /home/ijyothi/l4/pkg/virtio-net/server/p2p-link
vpath %.y /home/ijyothi/l4/pkg/virtio-net/server/p2p-link
vpath %.l /home/ijyothi/l4/pkg/virtio-net/server/p2p-link
vpath %.ld /home/ijyothi/l4/pkg/virtio-net/server/p2p-link
vpath %.dpe /home/ijyothi/l4/pkg/virtio-net/server/p2p-link
vpath %.dts /home/ijyothi/l4/pkg/virtio-net/server/p2p-link
.general.d: /home/ijyothi/l4/pkg/virtio-net/server/p2p-link/Makefile
include $(OBJ_BASE)/include/config/auto.conf
include /home/ijyothi/l4/pkg/virtio-net/server/p2p-link/Makefile
include $(L4DIR)/mk/prog.mk
