L4DIR=/home/ijyothi/l4
OBJ_BASE=/home/ijyothi/build-zynq
OBJ_DIR=/home/ijyothi/build-zynq/pkg/uvmm/tools/uvmm_cli
SRC_DIR=/home/ijyothi/l4/pkg/uvmm/tools/uvmm_cli
PKGDIR=/home/ijyothi/l4/pkg/uvmm
PKGDIR_ABS=/home/ijyothi/l4/pkg/uvmm
PKGDIR_OBJ=/home/ijyothi/build-zynq/pkg/uvmm
MAKECONFLOCAL=/home/ijyothi/l4/pkg/uvmm/tools/uvmm_cli/Makeconf.local
OSYSTEM=arm-l4f
SYSTEM=arm_armv7a-std-l4f
ARCH=arm
CPU=armv7a
L4API=l4f
VARIANT=std
vpath %.c /home/ijyothi/l4/pkg/uvmm/tools/uvmm_cli
vpath %.cc /home/ijyothi/l4/pkg/uvmm/tools/uvmm_cli
vpath %.cpp /home/ijyothi/l4/pkg/uvmm/tools/uvmm_cli
vpath %.f /home/ijyothi/l4/pkg/uvmm/tools/uvmm_cli
vpath %.F /home/ijyothi/l4/pkg/uvmm/tools/uvmm_cli
vpath %.f90 /home/ijyothi/l4/pkg/uvmm/tools/uvmm_cli
vpath %.F90 /home/ijyothi/l4/pkg/uvmm/tools/uvmm_cli
vpath %.f95 /home/ijyothi/l4/pkg/uvmm/tools/uvmm_cli
vpath %.F95 /home/ijyothi/l4/pkg/uvmm/tools/uvmm_cli
vpath %.S /home/ijyothi/l4/pkg/uvmm/tools/uvmm_cli
vpath %.y /home/ijyothi/l4/pkg/uvmm/tools/uvmm_cli
vpath %.l /home/ijyothi/l4/pkg/uvmm/tools/uvmm_cli
vpath %.ld /home/ijyothi/l4/pkg/uvmm/tools/uvmm_cli
vpath %.dpe /home/ijyothi/l4/pkg/uvmm/tools/uvmm_cli
vpath %.dts /home/ijyothi/l4/pkg/uvmm/tools/uvmm_cli
.general.d: /home/ijyothi/l4/pkg/uvmm/tools/uvmm_cli/Makefile
include $(OBJ_BASE)/include/config/auto.conf
include /home/ijyothi/l4/pkg/uvmm/tools/uvmm_cli/Makefile
include $(L4DIR)/mk/prog.mk
