L4DIR=/home/ijyothi/l4
OBJ_BASE=/home/ijyothi/build-zynq
OBJ_DIR=/home/ijyothi/build-zynq/pkg/atkins/selftest
SRC_DIR=/home/ijyothi/l4/pkg/atkins/selftest
PKGDIR=/home/ijyothi/l4/pkg/atkins
PKGDIR_ABS=/home/ijyothi/l4/pkg/atkins
PKGDIR_OBJ=/home/ijyothi/build-zynq/pkg/atkins
MAKECONFLOCAL=/home/ijyothi/l4/pkg/atkins/selftest/Makeconf.local
OSYSTEM=arm-l4f
SYSTEM=arm_armv7a-std-l4f
ARCH=arm
CPU=armv7a
L4API=l4f
VARIANT=std
vpath %.c /home/ijyothi/l4/pkg/atkins/selftest
vpath %.cc /home/ijyothi/l4/pkg/atkins/selftest
vpath %.cpp /home/ijyothi/l4/pkg/atkins/selftest
vpath %.f /home/ijyothi/l4/pkg/atkins/selftest
vpath %.F /home/ijyothi/l4/pkg/atkins/selftest
vpath %.f90 /home/ijyothi/l4/pkg/atkins/selftest
vpath %.F90 /home/ijyothi/l4/pkg/atkins/selftest
vpath %.f95 /home/ijyothi/l4/pkg/atkins/selftest
vpath %.F95 /home/ijyothi/l4/pkg/atkins/selftest
vpath %.S /home/ijyothi/l4/pkg/atkins/selftest
vpath %.y /home/ijyothi/l4/pkg/atkins/selftest
vpath %.l /home/ijyothi/l4/pkg/atkins/selftest
vpath %.ld /home/ijyothi/l4/pkg/atkins/selftest
vpath %.dpe /home/ijyothi/l4/pkg/atkins/selftest
vpath %.dts /home/ijyothi/l4/pkg/atkins/selftest
.general.d: /home/ijyothi/l4/pkg/atkins/selftest/Makefile
include $(OBJ_BASE)/include/config/auto.conf
include /home/ijyothi/l4/pkg/atkins/selftest/Makefile
include $(L4DIR)/mk/test.mk
