L4DIR=/home/ijyothi/l4
OBJ_BASE=/home/ijyothi/build-zynq
OBJ_DIR=/home/ijyothi/build-zynq/pkg/l4re-core/cxx/lib/io/src
SRC_DIR=/home/ijyothi/l4/pkg/l4re-core/cxx/lib/io/src
PKGDIR=/home/ijyothi/l4/pkg/l4re-core/cxx
PKGDIR_ABS=/home/ijyothi/l4/pkg/l4re-core/cxx
PKGDIR_OBJ=/home/ijyothi/build-zynq/pkg/l4re-core/cxx
MAKECONFLOCAL=/home/ijyothi/l4/pkg/l4re-core/cxx/lib/io/src/Makeconf.local
OSYSTEM=arm-plain
SYSTEM=arm_armv7a-std-plain
ARCH=arm
CPU=armv7a
L4API=plain
VARIANT=std
vpath %.c /home/ijyothi/l4/pkg/l4re-core/cxx/lib/io/src
vpath %.cc /home/ijyothi/l4/pkg/l4re-core/cxx/lib/io/src
vpath %.cpp /home/ijyothi/l4/pkg/l4re-core/cxx/lib/io/src
vpath %.f /home/ijyothi/l4/pkg/l4re-core/cxx/lib/io/src
vpath %.F /home/ijyothi/l4/pkg/l4re-core/cxx/lib/io/src
vpath %.f90 /home/ijyothi/l4/pkg/l4re-core/cxx/lib/io/src
vpath %.F90 /home/ijyothi/l4/pkg/l4re-core/cxx/lib/io/src
vpath %.f95 /home/ijyothi/l4/pkg/l4re-core/cxx/lib/io/src
vpath %.F95 /home/ijyothi/l4/pkg/l4re-core/cxx/lib/io/src
vpath %.S /home/ijyothi/l4/pkg/l4re-core/cxx/lib/io/src
vpath %.y /home/ijyothi/l4/pkg/l4re-core/cxx/lib/io/src
vpath %.l /home/ijyothi/l4/pkg/l4re-core/cxx/lib/io/src
vpath %.ld /home/ijyothi/l4/pkg/l4re-core/cxx/lib/io/src
vpath %.dpe /home/ijyothi/l4/pkg/l4re-core/cxx/lib/io/src
vpath %.dts /home/ijyothi/l4/pkg/l4re-core/cxx/lib/io/src
.general.d: /home/ijyothi/l4/pkg/l4re-core/cxx/lib/io/src/Makefile
include $(OBJ_BASE)/include/config/auto.conf
include /home/ijyothi/l4/pkg/l4re-core/cxx/lib/io/src/Makefile
include $(L4DIR)/mk/lib.mk
