L4DIR=/home/ijyothi/l4
OBJ_BASE=/home/ijyothi/build-zynq
OBJ_DIR=/home/ijyothi/build-zynq/pkg/io/io/server/src/drivers/gpio
SRC_DIR=/home/ijyothi/l4/pkg/io/io/server/src/drivers/gpio
PKGDIR=/home/ijyothi/l4/pkg/io/io
PKGDIR_ABS=/home/ijyothi/l4/pkg/io/io
PKGDIR_OBJ=/home/ijyothi/build-zynq/pkg/io/io
MAKECONFLOCAL=/home/ijyothi/l4/pkg/io/io/server/src/drivers/gpio/Makeconf.local
OSYSTEM=arm-l4f
SYSTEM=arm_armv7a-std-l4f
ARCH=arm
CPU=armv7a
L4API=l4f
VARIANT=std
vpath %.c /home/ijyothi/l4/pkg/io/io/server/src/drivers/gpio
vpath %.cc /home/ijyothi/l4/pkg/io/io/server/src/drivers/gpio
vpath %.cpp /home/ijyothi/l4/pkg/io/io/server/src/drivers/gpio
vpath %.f /home/ijyothi/l4/pkg/io/io/server/src/drivers/gpio
vpath %.F /home/ijyothi/l4/pkg/io/io/server/src/drivers/gpio
vpath %.f90 /home/ijyothi/l4/pkg/io/io/server/src/drivers/gpio
vpath %.F90 /home/ijyothi/l4/pkg/io/io/server/src/drivers/gpio
vpath %.f95 /home/ijyothi/l4/pkg/io/io/server/src/drivers/gpio
vpath %.F95 /home/ijyothi/l4/pkg/io/io/server/src/drivers/gpio
vpath %.S /home/ijyothi/l4/pkg/io/io/server/src/drivers/gpio
vpath %.y /home/ijyothi/l4/pkg/io/io/server/src/drivers/gpio
vpath %.l /home/ijyothi/l4/pkg/io/io/server/src/drivers/gpio
vpath %.ld /home/ijyothi/l4/pkg/io/io/server/src/drivers/gpio
vpath %.dpe /home/ijyothi/l4/pkg/io/io/server/src/drivers/gpio
vpath %.dts /home/ijyothi/l4/pkg/io/io/server/src/drivers/gpio
.general.d: /home/ijyothi/l4/pkg/io/io/server/src/drivers/gpio/Makefile
include $(OBJ_BASE)/include/config/auto.conf
include /home/ijyothi/l4/pkg/io/io/server/src/drivers/gpio/Makefile
include $(L4DIR)/mk/lib.mk
