L4DIR=/home/ijyothi/l4
OBJ_BASE=/home/ijyothi/build-zynq
OBJ_DIR=/home/ijyothi/build-zynq/pkg/l4re-core/libgcc-pure/lib
SRC_DIR=/home/ijyothi/l4/pkg/l4re-core/libgcc-pure/lib
PKGDIR=/home/ijyothi/l4/pkg/l4re-core/libgcc-pure
PKGDIR_ABS=/home/ijyothi/l4/pkg/l4re-core/libgcc-pure
PKGDIR_OBJ=/home/ijyothi/build-zynq/pkg/l4re-core/libgcc-pure
MAKECONFLOCAL=/home/ijyothi/l4/pkg/l4re-core/libgcc-pure/lib/Makeconf.local
OSYSTEM=arm-plain
SYSTEM=arm_armv7a-nofpu-plain
ARCH=arm
CPU=armv7a
L4API=plain
VARIANT=nofpu
vpath %.c /home/ijyothi/l4/pkg/l4re-core/libgcc-pure/lib
vpath %.cc /home/ijyothi/l4/pkg/l4re-core/libgcc-pure/lib
vpath %.cpp /home/ijyothi/l4/pkg/l4re-core/libgcc-pure/lib
vpath %.f /home/ijyothi/l4/pkg/l4re-core/libgcc-pure/lib
vpath %.F /home/ijyothi/l4/pkg/l4re-core/libgcc-pure/lib
vpath %.f90 /home/ijyothi/l4/pkg/l4re-core/libgcc-pure/lib
vpath %.F90 /home/ijyothi/l4/pkg/l4re-core/libgcc-pure/lib
vpath %.f95 /home/ijyothi/l4/pkg/l4re-core/libgcc-pure/lib
vpath %.F95 /home/ijyothi/l4/pkg/l4re-core/libgcc-pure/lib
vpath %.S /home/ijyothi/l4/pkg/l4re-core/libgcc-pure/lib
vpath %.y /home/ijyothi/l4/pkg/l4re-core/libgcc-pure/lib
vpath %.l /home/ijyothi/l4/pkg/l4re-core/libgcc-pure/lib
vpath %.ld /home/ijyothi/l4/pkg/l4re-core/libgcc-pure/lib
vpath %.dpe /home/ijyothi/l4/pkg/l4re-core/libgcc-pure/lib
vpath %.dts /home/ijyothi/l4/pkg/l4re-core/libgcc-pure/lib
.general.d: /home/ijyothi/l4/pkg/l4re-core/libgcc-pure/lib/Make.rules
include $(OBJ_BASE)/include/config/auto.conf
include /home/ijyothi/l4/pkg/l4re-core/libgcc-pure/lib/Make.rules
include $(L4DIR)/mk/lib.mk
