savedcmd___main.o := /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/bin/arm-none-linux-gnueabihf-gcc -c -MD -MP -MF ./.__main.o.d -DL4SYS_USE_UTCB_WRAP=1 -DSYSTEM_arm_armv7a_nofpu_l4f -DARCH_arm -DCPUTYPE_armv7a -DL4API_l4f -D_GNU_SOURCE -DBID_VARIANT_FLAG_NOFPU -march=armv7-a+fp -mgeneral-regs-only -I/home/ijyothi/l4/pkg/l4re-core/libgcc/generated/arm/gcc -I/home/ijyothi/l4/pkg/l4re-core/libgcc/generated/arm/libgcc -I/home/ijyothi/l4/pkg/l4re-core/libgcc/contrib/gcc-12/include -I/home/ijyothi/l4/pkg/l4re-core/libgcc/contrib/gcc-12/gcc -I/home/ijyothi/l4/pkg/l4re-core/libgcc/contrib/gcc-12/libgcc -I/home/ijyothi/l4/pkg/l4re-core/libgcc/contrib/gcc-12/libgcc/config/arm -I/home/ijyothi/build-zynq/pkg/l4re-core/libgcc/lib/src -I/home/ijyothi/build-zynq/include/arm/l4f -I/home/ijyothi/build-zynq/include/arm -I/home/ijyothi/build-zynq/include -I/home/ijyothi/build-zynq/include/contrib/libstdc++-v3 -nostdinc -I/home/ijyothi/build-zynq/include/uclibc -isystem /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/bin/../lib/gcc/arm-none-linux-gnueabihf/12.3.1/include -isystem /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/bin/../lib/gcc/arm-none-linux-gnueabihf/12.3.1/include-fixed -fno-omit-frame-pointer -fno-unwind-tables -g -O2 -fno-strict-aliasing -fno-common -std=gnu99 -marm -fmacro-prefix-map=/home/ijyothi/l4/= -fmacro-prefix-map=/home/ijyothi/build-zynq/= -march=armv7-a+fp -mgeneral-regs-only -fno-stack-protector -ffunction-sections -fdata-sections -O2 -g -O2 -DIN_GCC -DCROSS_DIRECTORY_STRUCTURE -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -DL4_LIBGCC_VERSION=12 -fPIC -g -DIN_LIBGCC2 -fbuilding-libgcc -fno-stack-protector -fvisibility=hidden -DHIDE_EXPORTS -DL__main /home/ijyothi/build-zynq/pkg/l4re-core/libgcc/lib/src/__main.c -o __main.o

source___main.o := /home/ijyothi/build-zynq/pkg/l4re-core/libgcc/lib/src/__main.c

deps___main.o := \
  /home/ijyothi/l4/pkg/l4re-core/libgcc/generated/arm/gcc/tconfig.h \
  /home/ijyothi/l4/pkg/l4re-core/libgcc/generated/arm/gcc/auto-host.h \
  /home/ijyothi/l4/pkg/l4re-core/libgcc/contrib/gcc-12/include/ansidecl.h \
  /home/ijyothi/l4/pkg/l4re-core/libgcc/contrib/gcc-12/gcc/tsystem.h \
  /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/lib/gcc/arm-none-linux-gnueabihf/12.3.1/include/stddef.h \
  /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/lib/gcc/arm-none-linux-gnueabihf/12.3.1/include/float.h \
  /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/lib/gcc/arm-none-linux-gnueabihf/12.3.1/include/stdarg.h \
  /home/ijyothi/build-zynq/include/uclibc/stdio.h \
  /home/ijyothi/build-zynq/include/uclibc/features.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/uClibc_config.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/l4-libc-symbols.h \
  /home/ijyothi/build-zynq/include/uclibc/sys/cdefs.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/types.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/wordsize.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/typesizes.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/uClibc_stdio.h \
  /home/ijyothi/build-zynq/include/uclibc/wchar.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/wchar.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/pthreadtypes.h \
  /home/ijyothi/build-zynq/include/l4/sys/types.h \
  /home/ijyothi/build-zynq/include/arm/l4/sys/l4int.h \
  /home/ijyothi/build-zynq/include/l4/sys/l4int.h \
  /home/ijyothi/build-zynq/include/l4/sys/compiler.h \
  /home/ijyothi/build-zynq/include/arm/l4/sys/linkage.h \
  /home/ijyothi/build-zynq/include/arm/l4/sys/consts.h \
  /home/ijyothi/build-zynq/include/l4/sys/consts.h \
  /home/ijyothi/build-zynq/include/l4/sys/__l4_fpage.h \
  /home/ijyothi/build-zynq/include/l4/sys/__timeout.h \
  /home/ijyothi/build-zynq/include/l4/sys/scheduler.h \
  /home/ijyothi/build-zynq/include/l4/sys/kernel_object.h \
  /home/ijyothi/build-zynq/include/arm/l4/sys/utcb.h \
  /home/ijyothi/build-zynq/include/l4/sys/utcb.h \
  /home/ijyothi/build-zynq/include/l4/sys/__kernel_object_impl.h \
  /home/ijyothi/build-zynq/include/arm/l4f/l4/sys/ipc.h \
  /home/ijyothi/build-zynq/include/l4/sys/ipc.h \
  /home/ijyothi/build-zynq/include/l4/sys/err.h \
  /home/ijyothi/build-zynq/include/arm/l4f/l4/sys/syscall_defs.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/sched.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/stdio_lim.h \
  /home/ijyothi/build-zynq/include/uclibc/sys/types.h \
  /home/ijyothi/build-zynq/include/uclibc/time.h \
  /home/ijyothi/build-zynq/include/uclibc/endian.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/endian.h \
  /home/ijyothi/build-zynq/include/uclibc/byteswap.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/byteswap.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/byteswap-common.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/byteswap-16.h \
  /home/ijyothi/build-zynq/include/uclibc/sys/select.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/select.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/sigset.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/time.h \
  /home/ijyothi/build-zynq/include/uclibc/sys/sysmacros.h \
  /home/ijyothi/build-zynq/include/uclibc/errno.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/errno.h \
  /home/ijyothi/build-zynq/include/uclibc/linux/errno.h \
  /home/ijyothi/build-zynq/include/uclibc/asm/errno.h \
  /home/ijyothi/build-zynq/include/uclibc/string.h \
  /home/ijyothi/build-zynq/include/uclibc/stdlib.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/waitflags.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/waitstatus.h \
  /home/ijyothi/build-zynq/include/uclibc/alloca.h \
  /home/ijyothi/build-zynq/include/uclibc/unistd.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/posix_opt.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/uClibc_posix_opt.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/environments.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/confname.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/getopt.h \
  /home/ijyothi/build-zynq/include/uclibc/limits.h \
  /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/lib/gcc/arm-none-linux-gnueabihf/12.3.1/include-fixed/limits.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/posix1_lim.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/local_lim.h \
  /home/ijyothi/build-zynq/include/uclibc/linux/limits.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/uClibc_local_lim.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/posix2_lim.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/xopen_lim.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/uClibc_clk_tck.h \
  /home/ijyothi/l4/pkg/l4re-core/libgcc/contrib/gcc-12/include/filenames.h \
  /home/ijyothi/l4/pkg/l4re-core/libgcc/contrib/gcc-12/include/hashtab.h \
  /home/ijyothi/l4/pkg/l4re-core/libgcc/contrib/gcc-12/gcc/coretypes.h \
  /home/ijyothi/l4/pkg/l4re-core/libgcc/generated/arm/gcc/tm.h \
  /home/ijyothi/l4/pkg/l4re-core/libgcc/contrib/gcc-12/gcc/config/dbxelf.h \
  /home/ijyothi/l4/pkg/l4re-core/libgcc/contrib/gcc-12/gcc/config/elfos.h \
  /home/ijyothi/l4/pkg/l4re-core/libgcc/contrib/gcc-12/gcc/config/arm/elf.h \
  /home/ijyothi/l4/pkg/l4re-core/libgcc/contrib/gcc-12/gcc/config/arm/bpabi.h \
  /home/ijyothi/l4/pkg/l4re-core/libgcc/contrib/gcc-12/gcc/config/arm/arm.h \
  /home/ijyothi/l4/pkg/l4re-core/libgcc/generated/arm/gcc/insn-modes.h \
  /home/ijyothi/l4/pkg/l4re-core/libgcc/contrib/gcc-12/gcc/config/vxworks-dummy.h \
  /home/ijyothi/l4/pkg/l4re-core/libgcc/contrib/gcc-12/gcc/config/arm/arm-opts.h \
  /home/ijyothi/l4/pkg/l4re-core/libgcc/contrib/gcc-12/gcc/config/arm/arm-flags.h \
  /home/ijyothi/l4/pkg/l4re-core/libgcc/generated/arm/gcc/arm-isa.h \
  /home/ijyothi/l4/pkg/l4re-core/libgcc/generated/arm/gcc/arm-cpu.h \
  /home/ijyothi/l4/pkg/l4re-core/libgcc/contrib/gcc-12/gcc/config/initfini-array.h \
  /home/ijyothi/l4/pkg/l4re-core/libgcc/contrib/gcc-12/gcc/defaults.h \
  /home/ijyothi/l4/pkg/l4re-core/libgcc/generated/arm/libgcc/libgcc_tm.h \
  /home/ijyothi/l4/pkg/l4re-core/libgcc/contrib/gcc-12/libgcc/config/arm/bpabi-lib.h \
  /home/ijyothi/l4/pkg/l4re-core/libgcc/contrib/gcc-12/libgcc/libgcc2.h \
  /home/ijyothi/l4/pkg/l4re-core/libgcc/contrib/gcc-12/include/longlong.h \
  /home/ijyothi/l4/pkg/l4re-core/libgcc/contrib/gcc-12/libgcc/gbl-ctors.h \

__main.o: $(deps___main.o)

$(deps___main.o):
