L4DIR=/home/ijyothi/l4
OBJ_BASE=/home/ijyothi/build-zynq
OBJ_DIR=/home/ijyothi/build-zynq/pkg/l4re-core/libgcc_eh-headers/include-gen
SRC_DIR=/home/ijyothi/l4/pkg/l4re-core/libgcc_eh-headers/include-gen
PKGDIR=/home/ijyothi/l4/pkg/l4re-core/libgcc_eh-headers
PKGDIR_ABS=/home/ijyothi/l4/pkg/l4re-core/libgcc_eh-headers
PKGDIR_OBJ=/home/ijyothi/build-zynq/pkg/l4re-core/libgcc_eh-headers
MAKECONFLOCAL=/home/ijyothi/l4/pkg/l4re-core/libgcc_eh-headers/include-gen/Makeconf.local
OSYSTEM=arm-l4f
SYSTEM=arm_armv7a-std-l4f
ARCH=arm
CPU=armv7a
L4API=l4f
VARIANT=std
vpath %.c /home/ijyothi/l4/pkg/l4re-core/libgcc_eh-headers/include-gen
vpath %.cc /home/ijyothi/l4/pkg/l4re-core/libgcc_eh-headers/include-gen
vpath %.cpp /home/ijyothi/l4/pkg/l4re-core/libgcc_eh-headers/include-gen
vpath %.f /home/ijyothi/l4/pkg/l4re-core/libgcc_eh-headers/include-gen
vpath %.F /home/ijyothi/l4/pkg/l4re-core/libgcc_eh-headers/include-gen
vpath %.f90 /home/ijyothi/l4/pkg/l4re-core/libgcc_eh-headers/include-gen
vpath %.F90 /home/ijyothi/l4/pkg/l4re-core/libgcc_eh-headers/include-gen
vpath %.f95 /home/ijyothi/l4/pkg/l4re-core/libgcc_eh-headers/include-gen
vpath %.F95 /home/ijyothi/l4/pkg/l4re-core/libgcc_eh-headers/include-gen
vpath %.S /home/ijyothi/l4/pkg/l4re-core/libgcc_eh-headers/include-gen
vpath %.y /home/ijyothi/l4/pkg/l4re-core/libgcc_eh-headers/include-gen
vpath %.l /home/ijyothi/l4/pkg/l4re-core/libgcc_eh-headers/include-gen
vpath %.ld /home/ijyothi/l4/pkg/l4re-core/libgcc_eh-headers/include-gen
vpath %.dpe /home/ijyothi/l4/pkg/l4re-core/libgcc_eh-headers/include-gen
vpath %.dts /home/ijyothi/l4/pkg/l4re-core/libgcc_eh-headers/include-gen
.general.d: /home/ijyothi/l4/pkg/l4re-core/libgcc_eh-headers/include-gen/Make.rules
include $(OBJ_BASE)/include/config/auto.conf
include /home/ijyothi/l4/pkg/l4re-core/libgcc_eh-headers/include-gen/Make.rules
include $(L4DIR)/mk/lib.mk
