L4DIR=/home/ijyothi/l4
OBJ_BASE=/home/ijyothi/build-zynq
OBJ_DIR=/home/ijyothi/build-zynq/conf/examples
SRC_DIR=/home/ijyothi/l4/conf/examples
PKGDIR=/home/ijyothi/l4/conf/examples
PKGDIR_ABS=/home/ijyothi/l4/conf/examples
PKGDIR_OBJ=/home/ijyothi/build-zynq/conf/examples
MAKECONFLOCAL=/home/ijyothi/l4/conf/examples/Makeconf.local
OSYSTEM=arm-l4f
SYSTEM=arm_armv7a-std-l4f
ARCH=arm
CPU=armv7a
L4API=l4f
VARIANT=std
vpath %.c /home/ijyothi/l4/conf/examples
vpath %.cc /home/ijyothi/l4/conf/examples
vpath %.cpp /home/ijyothi/l4/conf/examples
vpath %.f /home/ijyothi/l4/conf/examples
vpath %.F /home/ijyothi/l4/conf/examples
vpath %.f90 /home/ijyothi/l4/conf/examples
vpath %.F90 /home/ijyothi/l4/conf/examples
vpath %.f95 /home/ijyothi/l4/conf/examples
vpath %.F95 /home/ijyothi/l4/conf/examples
vpath %.S /home/ijyothi/l4/conf/examples
vpath %.y /home/ijyothi/l4/conf/examples
vpath %.l /home/ijyothi/l4/conf/examples
vpath %.ld /home/ijyothi/l4/conf/examples
vpath %.dpe /home/ijyothi/l4/conf/examples
vpath %.dts /home/ijyothi/l4/conf/examples
.general.d: /home/ijyothi/l4/conf/examples/Makefile
include $(OBJ_BASE)/include/config/auto.conf
include /home/ijyothi/l4/conf/examples/Makefile
include $(L4DIR)/mk/prog.mk
