L4DIR=/home/ijyothi/l4
OBJ_BASE=/home/ijyothi/build-zynq
OBJ_DIR=/home/ijyothi/build-zynq/pkg/io/io/server/src/drivers/pci
SRC_DIR=/home/ijyothi/l4/pkg/io/io/server/src/drivers/pci
PKGDIR=/home/ijyothi/l4/pkg/io/io
PKGDIR_ABS=/home/ijyothi/l4/pkg/io/io
PKGDIR_OBJ=/home/ijyothi/build-zynq/pkg/io/io
MAKECONFLOCAL=/home/ijyothi/l4/pkg/io/io/server/src/drivers/pci/Makeconf.local
OSYSTEM=arm-l4f
SYSTEM=arm_armv7a-std-l4f
ARCH=arm
CPU=armv7a
L4API=l4f
VARIANT=std
vpath %.c /home/ijyothi/l4/pkg/io/io/server/src/drivers/pci
vpath %.cc /home/ijyothi/l4/pkg/io/io/server/src/drivers/pci
vpath %.cpp /home/ijyothi/l4/pkg/io/io/server/src/drivers/pci
vpath %.f /home/ijyothi/l4/pkg/io/io/server/src/drivers/pci
vpath %.F /home/ijyothi/l4/pkg/io/io/server/src/drivers/pci
vpath %.f90 /home/ijyothi/l4/pkg/io/io/server/src/drivers/pci
vpath %.F90 /home/ijyothi/l4/pkg/io/io/server/src/drivers/pci
vpath %.f95 /home/ijyothi/l4/pkg/io/io/server/src/drivers/pci
vpath %.F95 /home/ijyothi/l4/pkg/io/io/server/src/drivers/pci
vpath %.S /home/ijyothi/l4/pkg/io/io/server/src/drivers/pci
vpath %.y /home/ijyothi/l4/pkg/io/io/server/src/drivers/pci
vpath %.l /home/ijyothi/l4/pkg/io/io/server/src/drivers/pci
vpath %.ld /home/ijyothi/l4/pkg/io/io/server/src/drivers/pci
vpath %.dpe /home/ijyothi/l4/pkg/io/io/server/src/drivers/pci
vpath %.dts /home/ijyothi/l4/pkg/io/io/server/src/drivers/pci
.general.d: /home/ijyothi/l4/pkg/io/io/server/src/drivers/pci/Makefile
include $(OBJ_BASE)/include/config/auto.conf
include /home/ijyothi/l4/pkg/io/io/server/src/drivers/pci/Makefile
include $(L4DIR)/mk/lib.mk
