L4DIR=/home/ijyothi/l4
OBJ_BASE=/home/ijyothi/build-zynq
OBJ_DIR=/home/ijyothi/build-zynq/pkg/l4re-core/cxx/lib/be/kdebug
SRC_DIR=/home/ijyothi/l4/pkg/l4re-core/cxx/lib/be/kdebug
PKGDIR=/home/ijyothi/l4/pkg/l4re-core/cxx
PKGDIR_ABS=/home/ijyothi/l4/pkg/l4re-core/cxx
PKGDIR_OBJ=/home/ijyothi/build-zynq/pkg/l4re-core/cxx
MAKECONFLOCAL=/home/ijyothi/l4/pkg/l4re-core/cxx/lib/be/kdebug/Makeconf.local
OSYSTEM=arm-l4f
SYSTEM=arm_armv7a-nofpu-l4f
ARCH=arm
CPU=armv7a
L4API=l4f
VARIANT=nofpu
vpath %.c /home/ijyothi/l4/pkg/l4re-core/cxx/lib/be/kdebug
vpath %.cc /home/ijyothi/l4/pkg/l4re-core/cxx/lib/be/kdebug
vpath %.cpp /home/ijyothi/l4/pkg/l4re-core/cxx/lib/be/kdebug
vpath %.f /home/ijyothi/l4/pkg/l4re-core/cxx/lib/be/kdebug
vpath %.F /home/ijyothi/l4/pkg/l4re-core/cxx/lib/be/kdebug
vpath %.f90 /home/ijyothi/l4/pkg/l4re-core/cxx/lib/be/kdebug
vpath %.F90 /home/ijyothi/l4/pkg/l4re-core/cxx/lib/be/kdebug
vpath %.f95 /home/ijyothi/l4/pkg/l4re-core/cxx/lib/be/kdebug
vpath %.F95 /home/ijyothi/l4/pkg/l4re-core/cxx/lib/be/kdebug
vpath %.S /home/ijyothi/l4/pkg/l4re-core/cxx/lib/be/kdebug
vpath %.y /home/ijyothi/l4/pkg/l4re-core/cxx/lib/be/kdebug
vpath %.l /home/ijyothi/l4/pkg/l4re-core/cxx/lib/be/kdebug
vpath %.ld /home/ijyothi/l4/pkg/l4re-core/cxx/lib/be/kdebug
vpath %.dpe /home/ijyothi/l4/pkg/l4re-core/cxx/lib/be/kdebug
vpath %.dts /home/ijyothi/l4/pkg/l4re-core/cxx/lib/be/kdebug
.general.d: /home/ijyothi/l4/pkg/l4re-core/cxx/lib/be/kdebug/Makefile
include $(OBJ_BASE)/include/config/auto.conf
include /home/ijyothi/l4/pkg/l4re-core/cxx/lib/be/kdebug/Makefile
include $(L4DIR)/mk/lib.mk
