L4DIR=/home/ijyothi/l4
OBJ_BASE=/home/ijyothi/build-zynq
OBJ_DIR=/home/ijyothi/build-zynq/tool/elf-util
SRC_DIR=/home/ijyothi/l4/tool/elf-util
PKGDIR=
PKGDIR_ABS=
PKGDIR_OBJ=/home/ijyothi/build-zynq/tool/elf-util
MAKECONFLOCAL=/home/ijyothi/l4/tool/elf-util/Makeconf.local
OSYSTEM=arm-l4f
SYSTEM=arm_armv7a-std-l4f
ARCH=arm
CPU=armv7a
L4API=l4f
VARIANT=std
vpath %.c /home/ijyothi/l4/tool/elf-util
vpath %.cc /home/ijyothi/l4/tool/elf-util
vpath %.cpp /home/ijyothi/l4/tool/elf-util
vpath %.f /home/ijyothi/l4/tool/elf-util
vpath %.F /home/ijyothi/l4/tool/elf-util
vpath %.f90 /home/ijyothi/l4/tool/elf-util
vpath %.F90 /home/ijyothi/l4/tool/elf-util
vpath %.f95 /home/ijyothi/l4/tool/elf-util
vpath %.F95 /home/ijyothi/l4/tool/elf-util
vpath %.S /home/ijyothi/l4/tool/elf-util
vpath %.y /home/ijyothi/l4/tool/elf-util
vpath %.l /home/ijyothi/l4/tool/elf-util
vpath %.ld /home/ijyothi/l4/tool/elf-util
vpath %.dpe /home/ijyothi/l4/tool/elf-util
vpath %.dts /home/ijyothi/l4/tool/elf-util
.general.d: /home/ijyothi/l4/tool/elf-util/Makefile
include $(OBJ_BASE)/include/config/auto.conf
include /home/ijyothi/l4/tool/elf-util/Makefile
include $(L4DIR)/mk/prog.mk
