L4DIR=/home/ijyothi/l4
OBJ_BASE=/home/ijyothi/build-zynq
OBJ_DIR=/home/ijyothi/build-zynq/pkg/readline/lib/readline
SRC_DIR=/home/ijyothi/l4/pkg/readline/lib/readline
PKGDIR=/home/ijyothi/l4/pkg/readline
PKGDIR_ABS=/home/ijyothi/l4/pkg/readline
PKGDIR_OBJ=/home/ijyothi/build-zynq/pkg/readline
MAKECONFLOCAL=/home/ijyothi/l4/pkg/readline/lib/readline/Makeconf.local
OSYSTEM=arm-l4f
SYSTEM=arm_armv7a-std-l4f
ARCH=arm
CPU=armv7a
L4API=l4f
VARIANT=std
vpath %.c /home/ijyothi/l4/pkg/readline/lib/readline
vpath %.cc /home/ijyothi/l4/pkg/readline/lib/readline
vpath %.cpp /home/ijyothi/l4/pkg/readline/lib/readline
vpath %.f /home/ijyothi/l4/pkg/readline/lib/readline
vpath %.F /home/ijyothi/l4/pkg/readline/lib/readline
vpath %.f90 /home/ijyothi/l4/pkg/readline/lib/readline
vpath %.F90 /home/ijyothi/l4/pkg/readline/lib/readline
vpath %.f95 /home/ijyothi/l4/pkg/readline/lib/readline
vpath %.F95 /home/ijyothi/l4/pkg/readline/lib/readline
vpath %.S /home/ijyothi/l4/pkg/readline/lib/readline
vpath %.y /home/ijyothi/l4/pkg/readline/lib/readline
vpath %.l /home/ijyothi/l4/pkg/readline/lib/readline
vpath %.ld /home/ijyothi/l4/pkg/readline/lib/readline
vpath %.dpe /home/ijyothi/l4/pkg/readline/lib/readline
vpath %.dts /home/ijyothi/l4/pkg/readline/lib/readline
.general.d: /home/ijyothi/l4/pkg/readline/lib/readline/Makefile
include $(OBJ_BASE)/include/config/auto.conf
include /home/ijyothi/l4/pkg/readline/lib/readline/Makefile
include $(L4DIR)/mk/lib.mk
