L4DIR=/home/ijyothi/l4
OBJ_BASE=/home/ijyothi/build-zynq
OBJ_DIR=/home/ijyothi/build-zynq/pkg/l4re-core/uclibc-minimal/libc
SRC_DIR=/home/ijyothi/l4/pkg/l4re-core/uclibc-minimal/libc
PKGDIR=/home/ijyothi/l4/pkg/l4re-core/uclibc-minimal
PKGDIR_ABS=/home/ijyothi/l4/pkg/l4re-core/uclibc-minimal
PKGDIR_OBJ=/home/ijyothi/build-zynq/pkg/l4re-core/uclibc-minimal
MAKECONFLOCAL=/home/ijyothi/l4/pkg/l4re-core/uclibc-minimal/libc/Makeconf.local
OSYSTEM=arm-plain
SYSTEM=arm_armv7a-std-plain
ARCH=arm
CPU=armv7a
L4API=plain
VARIANT=std
vpath %.c /home/ijyothi/l4/pkg/l4re-core/uclibc-minimal/libc
vpath %.cc /home/ijyothi/l4/pkg/l4re-core/uclibc-minimal/libc
vpath %.cpp /home/ijyothi/l4/pkg/l4re-core/uclibc-minimal/libc
vpath %.f /home/ijyothi/l4/pkg/l4re-core/uclibc-minimal/libc
vpath %.F /home/ijyothi/l4/pkg/l4re-core/uclibc-minimal/libc
vpath %.f90 /home/ijyothi/l4/pkg/l4re-core/uclibc-minimal/libc
vpath %.F90 /home/ijyothi/l4/pkg/l4re-core/uclibc-minimal/libc
vpath %.f95 /home/ijyothi/l4/pkg/l4re-core/uclibc-minimal/libc
vpath %.F95 /home/ijyothi/l4/pkg/l4re-core/uclibc-minimal/libc
vpath %.S /home/ijyothi/l4/pkg/l4re-core/uclibc-minimal/libc
vpath %.y /home/ijyothi/l4/pkg/l4re-core/uclibc-minimal/libc
vpath %.l /home/ijyothi/l4/pkg/l4re-core/uclibc-minimal/libc
vpath %.ld /home/ijyothi/l4/pkg/l4re-core/uclibc-minimal/libc
vpath %.dpe /home/ijyothi/l4/pkg/l4re-core/uclibc-minimal/libc
vpath %.dts /home/ijyothi/l4/pkg/l4re-core/uclibc-minimal/libc
.general.d: /home/ijyothi/l4/pkg/l4re-core/uclibc-minimal/libc/Make.rules
include $(OBJ_BASE)/include/config/auto.conf
include /home/ijyothi/l4/pkg/l4re-core/uclibc-minimal/libc/Make.rules
include $(L4DIR)/mk/lib.mk
