# automatically created -- modifications will be lost
SRC := /home/ijyothi/l4/pkg/l4re-core/libsupc++-minimal
OBJ := /home/ijyothi/build-zynq
.PHONY: $(MAKECMDGOALS) do-all-make-goals
do-all-make-goals:
	@PWD=$(SRC) $(MAKE) -C $(SRC) O=$(OBJ) $(MAKECMDGOALS)
$(MAKECMDGOALS): do-all-make-goals
