savedcmd_display.o := /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/bin/arm-none-linux-gnueabihf-gcc -c -MD -MP -MF ./.display.o.d -DL4SYS_USE_UTCB_WRAP=1 -DHAVE_CONFIG_H -D__L4 -DSYSTEM_arm_armv7a_nofpu_l4f -DARCH_arm -DCPUTYPE_armv7a -DL4API_l4f -D_GNU_SOURCE -DBID_VARIANT_FLAG_NOFPU -march=armv7-a+fp -mgeneral-regs-only -I/home/ijyothi/l4/pkg/readline/lib/readline -I/home/ijyothi/l4/pkg/readline/include -I/home/ijyothi/l4/pkg/readline/lib/contrib/libreadline -I/home/ijyothi/build-zynq/include/contrib/readline -I/home/ijyothi/build-zynq/include/contrib/libgcc_eh -I/home/ijyothi/build-zynq/include/arm/l4f -I/home/ijyothi/build-zynq/include/arm -I/home/ijyothi/build-zynq/include -I/home/ijyothi/build-zynq/include/contrib/libstdc++-v3 -nostdinc -I/home/ijyothi/build-zynq/include/uclibc -isystem /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/bin/../lib/gcc/arm-none-linux-gnueabihf/12.3.1/include -isystem /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/bin/../lib/gcc/arm-none-linux-gnueabihf/12.3.1/include-fixed -fno-omit-frame-pointer -fno-unwind-tables -g -O2 -fno-strict-aliasing -Wno-missing-prototypes -Wno-parentheses -fno-common -std=gnu99 -marm -fmacro-prefix-map=/home/ijyothi/l4/= -fmacro-prefix-map=/home/ijyothi/build-zynq/= -march=armv7-a+fp -mgeneral-regs-only -fno-stack-protector -ffunction-sections -fdata-sections -Wno-error=implicit-function-declaration -Wno-deprecated-non-prototype -include /home/ijyothi/l4/pkg/readline/lib/readline/posixselect.h /home/ijyothi/l4/pkg/readline/lib/contrib/libreadline/display.c -o display.o

source_display.o := /home/ijyothi/l4/pkg/readline/lib/contrib/libreadline/display.c

deps_display.o := \
  /home/ijyothi/l4/pkg/readline/lib/readline/posixselect.h \
  /home/ijyothi/l4/pkg/readline/lib/readline/config.h \
  /home/ijyothi/build-zynq/include/uclibc/sys/types.h \
  /home/ijyothi/build-zynq/include/uclibc/features.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/uClibc_config.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/l4-libc-symbols.h \
  /home/ijyothi/build-zynq/include/uclibc/sys/cdefs.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/types.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/wordsize.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/typesizes.h \
  /home/ijyothi/build-zynq/include/uclibc/time.h \
  /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/lib/gcc/arm-none-linux-gnueabihf/12.3.1/include/stddef.h \
  /home/ijyothi/build-zynq/include/uclibc/endian.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/endian.h \
  /home/ijyothi/build-zynq/include/uclibc/byteswap.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/byteswap.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/byteswap-common.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/byteswap-16.h \
  /home/ijyothi/build-zynq/include/uclibc/sys/select.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/select.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/sigset.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/time.h \
  /home/ijyothi/build-zynq/include/uclibc/sys/sysmacros.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/pthreadtypes.h \
  /home/ijyothi/build-zynq/include/l4/sys/types.h \
  /home/ijyothi/build-zynq/include/arm/l4/sys/l4int.h \
  /home/ijyothi/build-zynq/include/l4/sys/l4int.h \
  /home/ijyothi/build-zynq/include/l4/sys/compiler.h \
  /home/ijyothi/build-zynq/include/arm/l4/sys/linkage.h \
  /home/ijyothi/build-zynq/include/arm/l4/sys/consts.h \
  /home/ijyothi/build-zynq/include/l4/sys/consts.h \
  /home/ijyothi/build-zynq/include/l4/sys/__l4_fpage.h \
  /home/ijyothi/build-zynq/include/l4/sys/__timeout.h \
  /home/ijyothi/build-zynq/include/l4/sys/scheduler.h \
  /home/ijyothi/build-zynq/include/l4/sys/kernel_object.h \
  /home/ijyothi/build-zynq/include/arm/l4/sys/utcb.h \
  /home/ijyothi/build-zynq/include/l4/sys/utcb.h \
  /home/ijyothi/build-zynq/include/l4/sys/__kernel_object_impl.h \
  /home/ijyothi/build-zynq/include/arm/l4f/l4/sys/ipc.h \
  /home/ijyothi/build-zynq/include/l4/sys/ipc.h \
  /home/ijyothi/build-zynq/include/l4/sys/err.h \
  /home/ijyothi/build-zynq/include/arm/l4f/l4/sys/syscall_defs.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/sched.h \
  /home/ijyothi/build-zynq/include/uclibc/unistd.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/posix_opt.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/uClibc_posix_opt.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/environments.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/confname.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/getopt.h \
  /home/ijyothi/l4/pkg/readline/lib/contrib/libreadline/posixstat.h \
  /home/ijyothi/build-zynq/include/uclibc/sys/stat.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/stat.h \
  /home/ijyothi/build-zynq/include/uclibc/stdlib.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/waitflags.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/waitstatus.h \
  /home/ijyothi/build-zynq/include/uclibc/alloca.h \
  /home/ijyothi/build-zynq/include/uclibc/stdio.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/uClibc_stdio.h \
  /home/ijyothi/build-zynq/include/uclibc/wchar.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/wchar.h \
  /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/lib/gcc/arm-none-linux-gnueabihf/12.3.1/include/stdarg.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/stdio_lim.h \
  /home/ijyothi/l4/pkg/readline/lib/contrib/libreadline/rldefs.h \
  /home/ijyothi/l4/pkg/readline/lib/contrib/libreadline/rlstdc.h \
  /home/ijyothi/build-zynq/include/uclibc/string.h \
  /home/ijyothi/l4/pkg/readline/lib/contrib/libreadline/rlconf.h \
  /home/ijyothi/l4/pkg/readline/lib/contrib/libreadline/rlmbutil.h \
  /home/ijyothi/l4/pkg/readline/lib/contrib/libreadline/tcap.h \
  /home/ijyothi/l4/pkg/readline/lib/contrib/libreadline/readline.h \
  /home/ijyothi/l4/pkg/readline/lib/contrib/libreadline/rltypedefs.h \
  /home/ijyothi/l4/pkg/readline/lib/contrib/libreadline/keymaps.h \
  /home/ijyothi/l4/pkg/readline/lib/contrib/libreadline/chardefs.h \
  /home/ijyothi/build-zynq/include/uclibc/ctype.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/uClibc_touplow.h \
  /home/ijyothi/l4/pkg/readline/lib/contrib/libreadline/tilde.h \
  /home/ijyothi/l4/pkg/readline/lib/contrib/libreadline/history.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/uClibc_clk_tck.h \
  /home/ijyothi/l4/pkg/readline/lib/contrib/libreadline/rlprivate.h \
  /home/ijyothi/l4/pkg/readline/lib/contrib/libreadline/posixjmp.h \
  /home/ijyothi/build-zynq/include/uclibc/setjmp.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/setjmp.h \
  /home/ijyothi/l4/pkg/readline/lib/contrib/libreadline/xmalloc.h \

display.o: $(deps_display.o)

$(deps_display.o):
