L4DIR=/home/ijyothi/l4
OBJ_BASE=/home/ijyothi/build-zynq
OBJ_DIR=/home/ijyothi/build-zynq/pkg/l4re-core/ldso/libdl
SRC_DIR=/home/ijyothi/l4/pkg/l4re-core/ldso/libdl
PKGDIR=/home/ijyothi/l4/pkg/l4re-core/ldso
PKGDIR_ABS=/home/ijyothi/l4/pkg/l4re-core/ldso
PKGDIR_OBJ=/home/ijyothi/build-zynq/pkg/l4re-core/ldso
MAKECONFLOCAL=/home/ijyothi/l4/pkg/l4re-core/ldso/libdl/Makeconf.local
OSYSTEM=arm-l4f
SYSTEM=arm_armv7a-std-l4f
ARCH=arm
CPU=armv7a
L4API=l4f
VARIANT=std
vpath %.c /home/ijyothi/l4/pkg/l4re-core/ldso/libdl
vpath %.cc /home/ijyothi/l4/pkg/l4re-core/ldso/libdl
vpath %.cpp /home/ijyothi/l4/pkg/l4re-core/ldso/libdl
vpath %.f /home/ijyothi/l4/pkg/l4re-core/ldso/libdl
vpath %.F /home/ijyothi/l4/pkg/l4re-core/ldso/libdl
vpath %.f90 /home/ijyothi/l4/pkg/l4re-core/ldso/libdl
vpath %.F90 /home/ijyothi/l4/pkg/l4re-core/ldso/libdl
vpath %.f95 /home/ijyothi/l4/pkg/l4re-core/ldso/libdl
vpath %.F95 /home/ijyothi/l4/pkg/l4re-core/ldso/libdl
vpath %.S /home/ijyothi/l4/pkg/l4re-core/ldso/libdl
vpath %.y /home/ijyothi/l4/pkg/l4re-core/ldso/libdl
vpath %.l /home/ijyothi/l4/pkg/l4re-core/ldso/libdl
vpath %.ld /home/ijyothi/l4/pkg/l4re-core/ldso/libdl
vpath %.dpe /home/ijyothi/l4/pkg/l4re-core/ldso/libdl
vpath %.dts /home/ijyothi/l4/pkg/l4re-core/ldso/libdl
.general.d: /home/ijyothi/l4/pkg/l4re-core/ldso/libdl/Makefile
include $(OBJ_BASE)/include/config/auto.conf
include /home/ijyothi/l4/pkg/l4re-core/ldso/libdl/Makefile
include $(L4DIR)/mk/lib.mk
