L4DIR=/home/ijyothi/l4
OBJ_BASE=/home/ijyothi/build-zynq
OBJ_DIR=/home/ijyothi/build-zynq/pkg/l4re-core/libsigma0/lib/src
SRC_DIR=/home/ijyothi/l4/pkg/l4re-core/libsigma0/lib/src
PKGDIR=/home/ijyothi/l4/pkg/l4re-core/libsigma0
PKGDIR_ABS=/home/ijyothi/l4/pkg/l4re-core/libsigma0
PKGDIR_OBJ=/home/ijyothi/build-zynq/pkg/l4re-core/libsigma0
MAKECONFLOCAL=/home/ijyothi/l4/pkg/l4re-core/libsigma0/lib/src/Makeconf.local
OSYSTEM=arm-l4f
SYSTEM=arm_armv7a-std-l4f
ARCH=arm
CPU=armv7a
L4API=l4f
VARIANT=std
vpath %.c /home/ijyothi/l4/pkg/l4re-core/libsigma0/lib/src
vpath %.cc /home/ijyothi/l4/pkg/l4re-core/libsigma0/lib/src
vpath %.cpp /home/ijyothi/l4/pkg/l4re-core/libsigma0/lib/src
vpath %.f /home/ijyothi/l4/pkg/l4re-core/libsigma0/lib/src
vpath %.F /home/ijyothi/l4/pkg/l4re-core/libsigma0/lib/src
vpath %.f90 /home/ijyothi/l4/pkg/l4re-core/libsigma0/lib/src
vpath %.F90 /home/ijyothi/l4/pkg/l4re-core/libsigma0/lib/src
vpath %.f95 /home/ijyothi/l4/pkg/l4re-core/libsigma0/lib/src
vpath %.F95 /home/ijyothi/l4/pkg/l4re-core/libsigma0/lib/src
vpath %.S /home/ijyothi/l4/pkg/l4re-core/libsigma0/lib/src
vpath %.y /home/ijyothi/l4/pkg/l4re-core/libsigma0/lib/src
vpath %.l /home/ijyothi/l4/pkg/l4re-core/libsigma0/lib/src
vpath %.ld /home/ijyothi/l4/pkg/l4re-core/libsigma0/lib/src
vpath %.dpe /home/ijyothi/l4/pkg/l4re-core/libsigma0/lib/src
vpath %.dts /home/ijyothi/l4/pkg/l4re-core/libsigma0/lib/src
.general.d: /home/ijyothi/l4/pkg/l4re-core/libsigma0/lib/src/Makefile
include $(OBJ_BASE)/include/config/auto.conf
include /home/ijyothi/l4/pkg/l4re-core/libsigma0/lib/src/Makefile
include $(L4DIR)/mk/lib.mk
