L4DIR=/home/ijyothi/l4
OBJ_BASE=/home/ijyothi/build-zynq
OBJ_DIR=/home/ijyothi/build-zynq/pkg/l4re-core/l4re/util/libs
SRC_DIR=/home/ijyothi/l4/pkg/l4re-core/l4re/util/libs
PKGDIR=/home/ijyothi/l4/pkg/l4re-core/l4re
PKGDIR_ABS=/home/ijyothi/l4/pkg/l4re-core/l4re
PKGDIR_OBJ=/home/ijyothi/build-zynq/pkg/l4re-core/l4re
MAKECONFLOCAL=/home/ijyothi/l4/pkg/l4re-core/l4re/util/libs/Makeconf.local
OSYSTEM=arm-l4f
SYSTEM=arm_armv7a-std-l4f
ARCH=arm
CPU=armv7a
L4API=l4f
VARIANT=std
vpath %.c /home/ijyothi/l4/pkg/l4re-core/l4re/util/libs
vpath %.cc /home/ijyothi/l4/pkg/l4re-core/l4re/util/libs
vpath %.cpp /home/ijyothi/l4/pkg/l4re-core/l4re/util/libs
vpath %.f /home/ijyothi/l4/pkg/l4re-core/l4re/util/libs
vpath %.F /home/ijyothi/l4/pkg/l4re-core/l4re/util/libs
vpath %.f90 /home/ijyothi/l4/pkg/l4re-core/l4re/util/libs
vpath %.F90 /home/ijyothi/l4/pkg/l4re-core/l4re/util/libs
vpath %.f95 /home/ijyothi/l4/pkg/l4re-core/l4re/util/libs
vpath %.F95 /home/ijyothi/l4/pkg/l4re-core/l4re/util/libs
vpath %.S /home/ijyothi/l4/pkg/l4re-core/l4re/util/libs
vpath %.y /home/ijyothi/l4/pkg/l4re-core/l4re/util/libs
vpath %.l /home/ijyothi/l4/pkg/l4re-core/l4re/util/libs
vpath %.ld /home/ijyothi/l4/pkg/l4re-core/l4re/util/libs
vpath %.dpe /home/ijyothi/l4/pkg/l4re-core/l4re/util/libs
vpath %.dts /home/ijyothi/l4/pkg/l4re-core/l4re/util/libs
.general.d: /home/ijyothi/l4/pkg/l4re-core/l4re/util/libs/Makefile
include $(OBJ_BASE)/include/config/auto.conf
include /home/ijyothi/l4/pkg/l4re-core/l4re/util/libs/Makefile
include $(L4DIR)/mk/lib.mk
