L4DIR=/home/ijyothi/l4
OBJ_BASE=/home/ijyothi/build-zynq
OBJ_DIR=/home/ijyothi/build-zynq/pkg/l4re-core/uclibc/lib/minimal_l4re
SRC_DIR=/home/ijyothi/l4/pkg/l4re-core/uclibc/lib/minimal_l4re
PKGDIR=/home/ijyothi/l4/pkg/l4re-core/uclibc
PKGDIR_ABS=/home/ijyothi/l4/pkg/l4re-core/uclibc
PKGDIR_OBJ=/home/ijyothi/build-zynq/pkg/l4re-core/uclibc
MAKECONFLOCAL=/home/ijyothi/l4/pkg/l4re-core/uclibc/lib/minimal_l4re/Makeconf.local
OSYSTEM=arm-l4f
SYSTEM=arm_armv7a-nofpu-l4f
ARCH=arm
CPU=armv7a
L4API=l4f
VARIANT=nofpu
vpath %.c /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/minimal_l4re
vpath %.cc /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/minimal_l4re
vpath %.cpp /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/minimal_l4re
vpath %.f /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/minimal_l4re
vpath %.F /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/minimal_l4re
vpath %.f90 /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/minimal_l4re
vpath %.F90 /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/minimal_l4re
vpath %.f95 /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/minimal_l4re
vpath %.F95 /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/minimal_l4re
vpath %.S /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/minimal_l4re
vpath %.y /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/minimal_l4re
vpath %.l /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/minimal_l4re
vpath %.ld /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/minimal_l4re
vpath %.dpe /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/minimal_l4re
vpath %.dts /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/minimal_l4re
.general.d: /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/minimal_l4re/Makefile
include $(OBJ_BASE)/include/config/auto.conf
include /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/minimal_l4re/Makefile
include $(L4DIR)/mk/lib.mk
