L4DIR=/home/ijyothi/l4
OBJ_BASE=/home/ijyothi/build-zynq
OBJ_DIR=/home/ijyothi/build-zynq/pkg/libfdt/lib/build-host
SRC_DIR=/home/ijyothi/l4/pkg/libfdt/lib/build-host
PKGDIR=/home/ijyothi/l4/pkg/libfdt
PKGDIR_ABS=/home/ijyothi/l4/pkg/libfdt
PKGDIR_OBJ=/home/ijyothi/build-zynq/pkg/libfdt
MAKECONFLOCAL=/home/ijyothi/l4/pkg/libfdt/lib/build-host/Makeconf.local
OSYSTEM=arm-l4f
SYSTEM=arm_armv7a-nofpu-l4f
ARCH=arm
CPU=armv7a
L4API=l4f
VARIANT=nofpu
vpath %.c /home/ijyothi/l4/pkg/libfdt/lib/build-host
vpath %.cc /home/ijyothi/l4/pkg/libfdt/lib/build-host
vpath %.cpp /home/ijyothi/l4/pkg/libfdt/lib/build-host
vpath %.f /home/ijyothi/l4/pkg/libfdt/lib/build-host
vpath %.F /home/ijyothi/l4/pkg/libfdt/lib/build-host
vpath %.f90 /home/ijyothi/l4/pkg/libfdt/lib/build-host
vpath %.F90 /home/ijyothi/l4/pkg/libfdt/lib/build-host
vpath %.f95 /home/ijyothi/l4/pkg/libfdt/lib/build-host
vpath %.F95 /home/ijyothi/l4/pkg/libfdt/lib/build-host
vpath %.S /home/ijyothi/l4/pkg/libfdt/lib/build-host
vpath %.y /home/ijyothi/l4/pkg/libfdt/lib/build-host
vpath %.l /home/ijyothi/l4/pkg/libfdt/lib/build-host
vpath %.ld /home/ijyothi/l4/pkg/libfdt/lib/build-host
vpath %.dpe /home/ijyothi/l4/pkg/libfdt/lib/build-host
vpath %.dts /home/ijyothi/l4/pkg/libfdt/lib/build-host
.general.d: /home/ijyothi/l4/pkg/libfdt/lib/build-host/Makefile
include $(OBJ_BASE)/include/config/auto.conf
include /home/ijyothi/l4/pkg/libfdt/lib/build-host/Makefile
include $(L4DIR)/mk/lib.mk
