savedcmd_ARCH-arm/cpu_dev.o := /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/bin/arm-none-linux-gnueabihf-g++ -c -MD -MP -MF ARCH-arm/.cpu_dev.o.d -DSYSTEM_arm_armv7a_nofpu_l4f -DARCH_arm -DCPUTYPE_armv7a -DL4API_l4f -D_GNU_SOURCE -DBID_VARIANT_FLAG_NOFPU -mgeneral-regs-only -march=armv7ve+fp -I/home/ijyothi/l4/pkg/uvmm/server/src/../include -I/home/ijyothi/l4/pkg/uvmm/server/src -I/home/ijyothi/l4/pkg/uvmm/server/src/ARCH-arm -I/home/ijyothi/l4/pkg/uvmm/server/src/../../tools/uvmm_cli -I/home/ijyothi/l4/pkg/uvmm/server/src/arm -I/home/ijyothi/l4/pkg/uvmm/server/src/device/arm -I/home/ijyothi/build-zynq/include/contrib/libfdt -I/home/ijyothi/build-zynq/include/contrib/libstdc++-v3 -I/home/ijyothi/build-zynq/include/contrib/libgcc_eh -I/home/ijyothi/build-zynq/include/contrib/zlib -I/home/ijyothi/build-zynq/include/arm/l4f -I/home/ijyothi/build-zynq/include/arm -I/home/ijyothi/build-zynq/include -I/home/ijyothi/build-zynq/include/contrib/libstdc++-v3 -nostdinc -I/home/ijyothi/build-zynq/include/uclibc -isystem /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/bin/../lib/gcc/arm-none-linux-gnueabihf/12.3.1/include -isystem /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/bin/../lib/gcc/arm-none-linux-gnueabihf/12.3.1/include-fixed -fno-omit-frame-pointer -fno-unwind-tables -g -O3 -Wextra -Wdouble-promotion -Wfloat-conversion -Wfloat-equal -Wlogical-op -Wall -Wmissing-declarations -Wno-noexcept-type -Wno-psabi -fno-common -mgeneral-regs-only -march=armv7ve+fp -marm -fmacro-prefix-map=/home/ijyothi/l4/= -fmacro-prefix-map=/home/ijyothi/build-zynq/= -DL4_GCC_HAS_ATOMICS -fstack-protector -fuse-cxa-atexit -ffunction-sections -fdata-sections /home/ijyothi/l4/pkg/uvmm/server/src/ARCH-arm/cpu_dev.cc -o ARCH-arm/cpu_dev.o

source_ARCH-arm/cpu_dev.o := /home/ijyothi/l4/pkg/uvmm/server/src/ARCH-arm/cpu_dev.cc

deps_ARCH-arm/cpu_dev.o := \

ARCH-arm/cpu_dev.o: $(deps_ARCH-arm/cpu_dev.o)

$(deps_ARCH-arm/cpu_dev.o):
