L4DIR=/home/ijyothi/l4
OBJ_BASE=/home/ijyothi/build-zynq
OBJ_DIR=/home/ijyothi/build-zynq/pkg/l4re-core/ldscripts
SRC_DIR=/home/ijyothi/l4/pkg/l4re-core/ldscripts
PKGDIR=/home/ijyothi/l4/pkg/l4re-core/ldscripts
PKGDIR_ABS=/home/ijyothi/l4/pkg/l4re-core/ldscripts
PKGDIR_OBJ=/home/ijyothi/build-zynq/pkg/l4re-core/ldscripts
MAKECONFLOCAL=/home/ijyothi/l4/pkg/l4re-core/ldscripts/Makeconf.local
OSYSTEM=arm-plain
SYSTEM=arm_armv7a-std-plain
ARCH=arm
CPU=armv7a
L4API=plain
VARIANT=std
vpath %.c /home/ijyothi/l4/pkg/l4re-core/ldscripts
vpath %.cc /home/ijyothi/l4/pkg/l4re-core/ldscripts
vpath %.cpp /home/ijyothi/l4/pkg/l4re-core/ldscripts
vpath %.f /home/ijyothi/l4/pkg/l4re-core/ldscripts
vpath %.F /home/ijyothi/l4/pkg/l4re-core/ldscripts
vpath %.f90 /home/ijyothi/l4/pkg/l4re-core/ldscripts
vpath %.F90 /home/ijyothi/l4/pkg/l4re-core/ldscripts
vpath %.f95 /home/ijyothi/l4/pkg/l4re-core/ldscripts
vpath %.F95 /home/ijyothi/l4/pkg/l4re-core/ldscripts
vpath %.S /home/ijyothi/l4/pkg/l4re-core/ldscripts
vpath %.y /home/ijyothi/l4/pkg/l4re-core/ldscripts
vpath %.l /home/ijyothi/l4/pkg/l4re-core/ldscripts
vpath %.ld /home/ijyothi/l4/pkg/l4re-core/ldscripts
vpath %.dpe /home/ijyothi/l4/pkg/l4re-core/ldscripts
vpath %.dts /home/ijyothi/l4/pkg/l4re-core/ldscripts
.general.d: /home/ijyothi/l4/pkg/l4re-core/ldscripts/Makefile
include $(OBJ_BASE)/include/config/auto.conf
include /home/ijyothi/l4/pkg/l4re-core/ldscripts/Makefile
include $(L4DIR)/mk/lib.mk
