savedcmd_acpica/components/utilities/utmisc.o := /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/bin/arm-none-linux-gnueabihf-gcc -c -MD -MP -MF acpica/components/utilities/.utmisc.o.d -DL4SYS_USE_UTCB_WRAP=1 -DL4_ACPICA -DSYSTEM_arm_armv7a_std_l4f -DARCH_arm -DCPUTYPE_armv7a -DL4API_l4f -D_GNU_SOURCE -march=armv7-a+fp -I/home/ijyothi/build-zynq/include/contrib/acpica -I/home/ijyothi/build-zynq/include/contrib/libgcc_eh -I/home/ijyothi/build-zynq/include/arm/l4f -I/home/ijyothi/build-zynq/include/arm -I/home/ijyothi/build-zynq/include -I/home/ijyothi/build-zynq/include/contrib/libstdc++-v3 -nostdinc -I/home/ijyothi/build-zynq/include/uclibc -isystem /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/bin/../lib/gcc/arm-none-linux-gnueabihf/12.3.1/include -isystem /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/bin/../lib/gcc/arm-none-linux-gnueabihf/12.3.1/include-fixed -fno-omit-frame-pointer -fno-unwind-tables -g -O2 -fno-strict-aliasing -Wextra -Wbad-function-cast -Wdouble-promotion -Wfloat-conversion -Wfloat-equal -Wlogical-op -Wall -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wno-unused-parameter -Wno-null-pointer-subtraction -fno-common -std=gnu99 -marm -fmacro-prefix-map=/home/ijyothi/l4/= -fmacro-prefix-map=/home/ijyothi/build-zynq/= -march=armv7-a+fp -fno-stack-protector -ffunction-sections -fdata-sections /home/ijyothi/l4/pkg/acpica/lib-acpi/src/acpica/components/utilities/utmisc.c -o acpica/components/utilities/utmisc.o

source_acpica/components/utilities/utmisc.o := /home/ijyothi/l4/pkg/acpica/lib-acpi/src/acpica/components/utilities/utmisc.c

deps_acpica/components/utilities/utmisc.o := \
  /home/ijyothi/build-zynq/include/contrib/acpica/acpi.h \
  /home/ijyothi/build-zynq/include/contrib/acpica/platform/acenv.h \
  /home/ijyothi/build-zynq/include/contrib/acpica/platform/acgcc.h \
  /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/lib/gcc/arm-none-linux-gnueabihf/12.3.1/include/stdarg.h \
  /home/ijyothi/build-zynq/include/contrib/acpica/platform/acl4.h \
  /home/ijyothi/build-zynq/include/arm/l4/sys/l4int.h \
  /home/ijyothi/build-zynq/include/l4/sys/l4int.h \
  /home/ijyothi/build-zynq/include/uclibc/pthread.h \
  /home/ijyothi/build-zynq/include/uclibc/features.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/uClibc_config.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/l4-libc-symbols.h \
  /home/ijyothi/build-zynq/include/uclibc/sys/cdefs.h \
  /home/ijyothi/build-zynq/include/uclibc/sched.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/types.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/wordsize.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/typesizes.h \
  /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/lib/gcc/arm-none-linux-gnueabihf/12.3.1/include/stddef.h \
  /home/ijyothi/build-zynq/include/uclibc/time.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/sched.h \
  /home/ijyothi/build-zynq/include/uclibc/stdlib.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/waitflags.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/waitstatus.h \
  /home/ijyothi/build-zynq/include/uclibc/endian.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/endian.h \
  /home/ijyothi/build-zynq/include/uclibc/byteswap.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/byteswap.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/byteswap-common.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/byteswap-16.h \
  /home/ijyothi/build-zynq/include/uclibc/sys/types.h \
  /home/ijyothi/build-zynq/include/uclibc/sys/select.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/select.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/sigset.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/time.h \
  /home/ijyothi/build-zynq/include/uclibc/sys/sysmacros.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/pthreadtypes.h \
  /home/ijyothi/build-zynq/include/l4/sys/types.h \
  /home/ijyothi/build-zynq/include/l4/sys/compiler.h \
  /home/ijyothi/build-zynq/include/arm/l4/sys/linkage.h \
  /home/ijyothi/build-zynq/include/arm/l4/sys/consts.h \
  /home/ijyothi/build-zynq/include/l4/sys/consts.h \
  /home/ijyothi/build-zynq/include/l4/sys/__l4_fpage.h \
  /home/ijyothi/build-zynq/include/l4/sys/__timeout.h \
  /home/ijyothi/build-zynq/include/l4/sys/scheduler.h \
  /home/ijyothi/build-zynq/include/l4/sys/kernel_object.h \
  /home/ijyothi/build-zynq/include/arm/l4/sys/utcb.h \
  /home/ijyothi/build-zynq/include/l4/sys/utcb.h \
  /home/ijyothi/build-zynq/include/l4/sys/__kernel_object_impl.h \
  /home/ijyothi/build-zynq/include/arm/l4f/l4/sys/ipc.h \
  /home/ijyothi/build-zynq/include/l4/sys/ipc.h \
  /home/ijyothi/build-zynq/include/l4/sys/err.h \
  /home/ijyothi/build-zynq/include/arm/l4f/l4/sys/syscall_defs.h \
  /home/ijyothi/build-zynq/include/uclibc/alloca.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/uClibc_clk_tck.h \
  /home/ijyothi/build-zynq/include/uclibc/signal.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/initspin.h \
  /home/ijyothi/build-zynq/include/uclibc/string.h \
  /home/ijyothi/build-zynq/include/uclibc/ctype.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/uClibc_touplow.h \
  /home/ijyothi/build-zynq/include/contrib/acpica/actypes.h \
  /home/ijyothi/build-zynq/include/contrib/acpica/platform/acenvex.h \
  /home/ijyothi/build-zynq/include/contrib/acpica/platform/aclinuxex.h \
  /home/ijyothi/build-zynq/include/contrib/acpica/platform/acgccex.h \
  /home/ijyothi/build-zynq/include/contrib/acpica/acnames.h \
  /home/ijyothi/build-zynq/include/contrib/acpica/acexcep.h \
  /home/ijyothi/build-zynq/include/contrib/acpica/actbl.h \
  /home/ijyothi/build-zynq/include/contrib/acpica/actbl1.h \
  /home/ijyothi/build-zynq/include/contrib/acpica/actbl2.h \
  /home/ijyothi/build-zynq/include/contrib/acpica/actbl3.h \
  /home/ijyothi/build-zynq/include/contrib/acpica/acoutput.h \
  /home/ijyothi/build-zynq/include/contrib/acpica/acrestyp.h \
  /home/ijyothi/build-zynq/include/contrib/acpica/acpiosxf.h \
  /home/ijyothi/build-zynq/include/contrib/acpica/acpixf.h \
  /home/ijyothi/build-zynq/include/contrib/acpica/acconfig.h \
  /home/ijyothi/build-zynq/include/contrib/acpica/acbuffer.h \
  /home/ijyothi/build-zynq/include/contrib/acpica/accommon.h \
  /home/ijyothi/build-zynq/include/contrib/acpica/acmacros.h \
  /home/ijyothi/build-zynq/include/contrib/acpica/aclocal.h \
  /home/ijyothi/build-zynq/include/contrib/acpica/acobject.h \
  /home/ijyothi/build-zynq/include/contrib/acpica/acstruct.h \
  /home/ijyothi/build-zynq/include/contrib/acpica/acglobal.h \
  /home/ijyothi/build-zynq/include/contrib/acpica/achware.h \
  /home/ijyothi/build-zynq/include/contrib/acpica/acutils.h \
  /home/ijyothi/build-zynq/include/contrib/acpica/acnamesp.h \

acpica/components/utilities/utmisc.o: $(deps_acpica/components/utilities/utmisc.o)

$(deps_acpica/components/utilities/utmisc.o):
