L4DIR=/home/ijyothi/l4
OBJ_BASE=/home/ijyothi/build-zynq
OBJ_DIR=/home/ijyothi/build-zynq/pkg/virtio-net-switch/server/switch
SRC_DIR=/home/ijyothi/l4/pkg/virtio-net-switch/server/switch
PKGDIR=/home/ijyothi/l4/pkg/virtio-net-switch
PKGDIR_ABS=/home/ijyothi/l4/pkg/virtio-net-switch
PKGDIR_OBJ=/home/ijyothi/build-zynq/pkg/virtio-net-switch
MAKECONFLOCAL=/home/ijyothi/l4/pkg/virtio-net-switch/server/switch/Makeconf.local
OSYSTEM=arm-l4f
SYSTEM=arm_armv7a-std-l4f
ARCH=arm
CPU=armv7a
L4API=l4f
VARIANT=std
vpath %.c /home/ijyothi/l4/pkg/virtio-net-switch/server/switch
vpath %.cc /home/ijyothi/l4/pkg/virtio-net-switch/server/switch
vpath %.cpp /home/ijyothi/l4/pkg/virtio-net-switch/server/switch
vpath %.f /home/ijyothi/l4/pkg/virtio-net-switch/server/switch
vpath %.F /home/ijyothi/l4/pkg/virtio-net-switch/server/switch
vpath %.f90 /home/ijyothi/l4/pkg/virtio-net-switch/server/switch
vpath %.F90 /home/ijyothi/l4/pkg/virtio-net-switch/server/switch
vpath %.f95 /home/ijyothi/l4/pkg/virtio-net-switch/server/switch
vpath %.F95 /home/ijyothi/l4/pkg/virtio-net-switch/server/switch
vpath %.S /home/ijyothi/l4/pkg/virtio-net-switch/server/switch
vpath %.y /home/ijyothi/l4/pkg/virtio-net-switch/server/switch
vpath %.l /home/ijyothi/l4/pkg/virtio-net-switch/server/switch
vpath %.ld /home/ijyothi/l4/pkg/virtio-net-switch/server/switch
vpath %.dpe /home/ijyothi/l4/pkg/virtio-net-switch/server/switch
vpath %.dts /home/ijyothi/l4/pkg/virtio-net-switch/server/switch
.general.d: /home/ijyothi/l4/pkg/virtio-net-switch/server/switch/Makefile
include $(OBJ_BASE)/include/config/auto.conf
include /home/ijyothi/l4/pkg/virtio-net-switch/server/switch/Makefile
include $(L4DIR)/mk/prog.mk
