savedcmd_specific.s.o := /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/bin/arm-none-linux-gnueabihf-gcc -c -MD -MP -MF ./.specific.s.o.d -DL4SYS_USE_UTCB_WRAP=1 -DL4_THREAD_SAFE -D__USE_XOPEN2K -D_POSIX_C_SOURCE=200112L -D_GNU_SOURCE=1 -D__NO_WEAK_PTHREAD_ALIASES=1 -D_LIBC=1 -DIS_IN_libpthread=1 -DNOT_IN_libc=1 -DSYSTEM_arm_armv7a_std_l4f -DARCH_arm -DCPUTYPE_armv7a -DL4API_l4f -D_GNU_SOURCE -DUSE___THREAD=1 -march=armv7-a+fp -I/home/ijyothi/l4/pkg/l4re-core/uclibc/lib/libpthread/src -I/home/ijyothi/l4/pkg/l4re-core/uclibc/lib/libpthread/src/sysdeps/arm -I/home/ijyothi/l4/pkg/l4re-core/uclibc/../uclibc/lib/contrib/uclibc/ldso/include -I/home/ijyothi/build-zynq/include/contrib/libgcc_eh -I/home/ijyothi/build-zynq/include/arm/l4f -I/home/ijyothi/build-zynq/include/arm -I/home/ijyothi/build-zynq/include -I/home/ijyothi/build-zynq/include/contrib/libstdc++-v3 -nostdinc -I/home/ijyothi/build-zynq/include/uclibc -isystem /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/bin/../lib/gcc/arm-none-linux-gnueabihf/12.3.1/include -isystem /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/bin/../lib/gcc/arm-none-linux-gnueabihf/12.3.1/include-fixed -include /home/ijyothi/l4/pkg/l4re-core/uclibc/../uclibc/lib/contrib/uclibc/include/libc-symbols.h -fno-omit-frame-pointer -fno-unwind-tables -g -O2 -fno-strict-aliasing -Wall -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -fno-common -std=gnu99 -marm -fmacro-prefix-map=/home/ijyothi/l4/= -fmacro-prefix-map=/home/ijyothi/build-zynq/= -march=armv7-a+fp -fno-stack-protector -ffunction-sections -fdata-sections -fPIC -U__PIC__ -D__PIC__=1 -DSHARED /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/libpthread/src/specific.c -o specific.s.o

source_specific.s.o := /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/libpthread/src/specific.c

deps_specific.s.o := \
  /home/ijyothi/l4/pkg/l4re-core/uclibc/../uclibc/lib/contrib/uclibc/include/libc-symbols.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/uClibc_arch_features.h \
  /home/ijyothi/build-zynq/include/uclibc/errno.h \
  /home/ijyothi/build-zynq/include/uclibc/features.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/uClibc_config.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/l4-libc-symbols.h \
  /home/ijyothi/build-zynq/include/uclibc/sys/cdefs.h \
  /home/ijyothi/build-zynq/include/uclibc/libc-internal.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/errno.h \
  /home/ijyothi/build-zynq/include/uclibc/linux/errno.h \
  /home/ijyothi/build-zynq/include/uclibc/asm/errno.h \
  /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/lib/gcc/arm-none-linux-gnueabihf/12.3.1/include/stddef.h \
  /home/ijyothi/build-zynq/include/uclibc/stdlib.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/waitflags.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/waitstatus.h \
  /home/ijyothi/build-zynq/include/uclibc/endian.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/endian.h \
  /home/ijyothi/build-zynq/include/uclibc/stdint.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/wchar.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/wordsize.h \
  /home/ijyothi/build-zynq/include/uclibc/byteswap.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/byteswap.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/byteswap-common.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/types.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/kernel_types.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/typesizes.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/byteswap-16.h \
  /home/ijyothi/build-zynq/include/uclibc/sys/types.h \
  /home/ijyothi/build-zynq/include/uclibc/time.h \
  /home/ijyothi/build-zynq/include/uclibc/sys/select.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/select.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/sigset.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/time.h \
  /home/ijyothi/build-zynq/include/uclibc/sys/sysmacros.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/pthreadtypes.h \
  /home/ijyothi/build-zynq/include/l4/sys/types.h \
  /home/ijyothi/build-zynq/include/arm/l4/sys/l4int.h \
  /home/ijyothi/build-zynq/include/l4/sys/l4int.h \
  /home/ijyothi/build-zynq/include/l4/sys/compiler.h \
  /home/ijyothi/build-zynq/include/arm/l4/sys/linkage.h \
  /home/ijyothi/build-zynq/include/arm/l4/sys/consts.h \
  /home/ijyothi/build-zynq/include/l4/sys/consts.h \
  /home/ijyothi/build-zynq/include/l4/sys/__l4_fpage.h \
  /home/ijyothi/build-zynq/include/l4/sys/__timeout.h \
  /home/ijyothi/build-zynq/include/l4/sys/scheduler.h \
  /home/ijyothi/build-zynq/include/l4/sys/kernel_object.h \
  /home/ijyothi/build-zynq/include/arm/l4/sys/utcb.h \
  /home/ijyothi/build-zynq/include/l4/sys/utcb.h \
  /home/ijyothi/build-zynq/include/l4/sys/__kernel_object_impl.h \
  /home/ijyothi/build-zynq/include/arm/l4f/l4/sys/ipc.h \
  /home/ijyothi/build-zynq/include/l4/sys/ipc.h \
  /home/ijyothi/build-zynq/include/l4/sys/err.h \
  /home/ijyothi/build-zynq/include/arm/l4f/l4/sys/syscall_defs.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/sched.h \
  /home/ijyothi/build-zynq/include/uclibc/alloca.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/stackinfo.h \
  /home/ijyothi/build-zynq/include/uclibc/pthread.h \
  /home/ijyothi/build-zynq/include/uclibc/sched.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/uClibc_clk_tck.h \
  /home/ijyothi/build-zynq/include/uclibc/signal.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/initspin.h \
  /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/libpthread/src/internals.h \
  /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/libpthread/src/uClibc-glue.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/uClibc_page.h \
  /home/ijyothi/build-zynq/include/uclibc/limits.h \
  /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/lib/gcc/arm-none-linux-gnueabihf/12.3.1/include-fixed/limits.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/posix1_lim.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/local_lim.h \
  /home/ijyothi/build-zynq/include/uclibc/linux/limits.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/uClibc_local_lim.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/posix2_lim.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/xopen_lim.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/stdio_lim.h \
  /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/lib/gcc/arm-none-linux-gnueabihf/12.3.1/include/stdbool.h \
  /home/ijyothi/build-zynq/include/uclibc/unistd.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/posix_opt.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/uClibc_posix_opt.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/environments.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/confname.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/getopt.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/libc-lock.h \
  /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/libpthread/src/descr.h \
    $(wildcard include/config/L4) \
  /home/ijyothi/build-zynq/include/uclibc/resolv.h \
  /home/ijyothi/build-zynq/include/uclibc/netinet/in.h \
  /home/ijyothi/build-zynq/include/uclibc/sys/socket.h \
  /home/ijyothi/build-zynq/include/uclibc/sys/uio.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/uio.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/socket.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/socket_type.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/sockaddr.h \
  /home/ijyothi/build-zynq/include/uclibc/asm/socket.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/in.h \
  /home/ijyothi/build-zynq/include/uclibc/setjmp.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/setjmp.h \
  /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/libpthread/src/sysdeps/arm/tls.h \
  /home/ijyothi/build-zynq/include/arm/l4/sys/thread.h \
  /home/ijyothi/build-zynq/include/l4/sys/thread.h \
  /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/libpthread/src/sysdeps/arm/../../descr.h \
  /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/libpthread/src/sysdeps/arm/pt-machine.h \
  /home/ijyothi/build-zynq/include/uclibc/semaphore.h \
  /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/libpthread/src/pthread-functions.h \
  /home/ijyothi/build-zynq/include/l4/sys/kdebug.h \
  /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/libpthread/src/spinlock.h \
  /home/ijyothi/l4/pkg/l4re-core/uclibc/lib/libpthread/src/restart.h \
  /home/ijyothi/build-zynq/include/l4/sys/semaphore.h \
  /home/ijyothi/build-zynq/include/l4/sys/irq.h \
  /home/ijyothi/build-zynq/include/l4/sys/rcv_endpoint.h \
  /home/ijyothi/build-zynq/include/uclibc/stdio.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/uClibc_stdio.h \
  /home/ijyothi/build-zynq/include/uclibc/wchar.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/uClibc_mutex.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/uClibc_pthread.h \
  /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/lib/gcc/arm-none-linux-gnueabihf/12.3.1/include/stdarg.h \

specific.s.o: $(deps_specific.s.o)

$(deps_specific.s.o):
