L4DIR=/home/ijyothi/l4
OBJ_BASE=/home/ijyothi/build-zynq
OBJ_DIR=/home/ijyothi/build-zynq/pkg/l4re-core/libsupc++-minimal
SRC_DIR=/home/ijyothi/l4/pkg/l4re-core/libsupc++-minimal
PKGDIR=/home/ijyothi/l4/pkg/l4re-core/libsupc++-minimal
PKGDIR_ABS=/home/ijyothi/l4/pkg/l4re-core/libsupc++-minimal
PKGDIR_OBJ=/home/ijyothi/build-zynq/pkg/l4re-core/libsupc++-minimal
MAKECONFLOCAL=/home/ijyothi/l4/pkg/l4re-core/libsupc++-minimal/Makeconf.local
OSYSTEM=arm-l4f
SYSTEM=arm_armv7a-std-l4f
ARCH=arm
CPU=armv7a
L4API=l4f
VARIANT=std
vpath %.c ./../libstdc++-v3/contrib/libstdc++-v3-12/libsupc++
vpath %.cc ./../libstdc++-v3/contrib/libstdc++-v3-12/libsupc++
vpath %.cpp ./../libstdc++-v3/contrib/libstdc++-v3-12/libsupc++
vpath %.f ./../libstdc++-v3/contrib/libstdc++-v3-12/libsupc++
vpath %.F ./../libstdc++-v3/contrib/libstdc++-v3-12/libsupc++
vpath %.f90 ./../libstdc++-v3/contrib/libstdc++-v3-12/libsupc++
vpath %.F90 ./../libstdc++-v3/contrib/libstdc++-v3-12/libsupc++
vpath %.f95 ./../libstdc++-v3/contrib/libstdc++-v3-12/libsupc++
vpath %.F95 ./../libstdc++-v3/contrib/libstdc++-v3-12/libsupc++
vpath %.S ./../libstdc++-v3/contrib/libstdc++-v3-12/libsupc++
vpath %.y ./../libstdc++-v3/contrib/libstdc++-v3-12/libsupc++
vpath %.l ./../libstdc++-v3/contrib/libstdc++-v3-12/libsupc++
vpath %.ld ./../libstdc++-v3/contrib/libstdc++-v3-12/libsupc++
vpath %.dpe ./../libstdc++-v3/contrib/libstdc++-v3-12/libsupc++
vpath %.dts ./../libstdc++-v3/contrib/libstdc++-v3-12/libsupc++
.general.d: /home/ijyothi/l4/pkg/l4re-core/libsupc++-minimal/Makefile
include $(OBJ_BASE)/include/config/auto.conf
include /home/ijyothi/l4/pkg/l4re-core/libsupc++-minimal/Makefile
include $(L4DIR)/mk/lib.mk
