savedcmd_arm_dma_device.o := /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/bin/arm-none-linux-gnueabihf-g++ -c -MD -MP -MF ./.arm_dma_device.o.d -DSYSTEM_arm_armv7a_std_l4f -DARCH_arm -DCPUTYPE_armv7a -DL4API_l4f -D_GNU_SOURCE -DCONFIG_L4IO_PCIID_DB -march=armv7-a+fp -I/home/ijyothi/l4/pkg/io/io/server/src -I/home/ijyothi/l4/pkg/io/io/server/src/../libpciids/include -I/home/ijyothi/build-zynq/include/contrib/libio-io -I/home/ijyothi/build-zynq/include/contrib/lua -I/home/ijyothi/build-zynq/include/contrib/libstdc++-v3 -I/home/ijyothi/build-zynq/include/contrib/libgcc_eh -I/home/ijyothi/build-zynq/include/arm/l4f -I/home/ijyothi/build-zynq/include/arm -I/home/ijyothi/build-zynq/include -I/home/ijyothi/build-zynq/include/contrib/libstdc++-v3 -nostdinc -I/home/ijyothi/build-zynq/include/uclibc -isystem /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/bin/../lib/gcc/arm-none-linux-gnueabihf/12.3.1/include -isystem /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/bin/../lib/gcc/arm-none-linux-gnueabihf/12.3.1/include-fixed -fno-omit-frame-pointer -fno-unwind-tables -g -O3 -Wextra -Wdouble-promotion -Wfloat-conversion -Wfloat-equal -Wlogical-op -Wall -Wmissing-declarations -Wno-noexcept-type -Wno-psabi -fno-common -march=armv7-a+fp -marm -fmacro-prefix-map=/home/ijyothi/l4/= -fmacro-prefix-map=/home/ijyothi/build-zynq/= -DL4_GCC_HAS_ATOMICS -fstack-protector -fuse-cxa-atexit -ffunction-sections -fdata-sections /home/ijyothi/l4/pkg/io/io/server/src/arm_dma_device.cc -o arm_dma_device.o

source_arm_dma_device.o := /home/ijyothi/l4/pkg/io/io/server/src/arm_dma_device.cc

deps_arm_dma_device.o := \
  /home/ijyothi/l4/pkg/io/io/server/src/arm_dma_device.h \
  /home/ijyothi/l4/pkg/io/io/server/src/arm_dma_domain.h \
  /home/ijyothi/build-zynq/include/l4/re/env \
  /home/ijyothi/build-zynq/include/l4/sys/types.h \
  /home/ijyothi/build-zynq/include/arm/l4/sys/l4int.h \
  /home/ijyothi/build-zynq/include/l4/sys/l4int.h \
  /home/ijyothi/build-zynq/include/l4/sys/compiler.h \
  /home/ijyothi/build-zynq/include/arm/l4/sys/linkage.h \
  /home/ijyothi/build-zynq/include/arm/l4/sys/consts.h \
  /home/ijyothi/build-zynq/include/l4/sys/consts.h \
  /home/ijyothi/build-zynq/include/l4/sys/__l4_fpage.h \
  /home/ijyothi/build-zynq/include/l4/sys/__timeout.h \
  /home/ijyothi/build-zynq/include/l4/re/rm \
  /home/ijyothi/build-zynq/include/l4/sys/capability \
  /home/ijyothi/build-zynq/include/l4/sys/kobject \
  /home/ijyothi/build-zynq/include/l4/sys/kernel_object.h \
  /home/ijyothi/build-zynq/include/arm/l4/sys/utcb.h \
  /home/ijyothi/build-zynq/include/l4/sys/utcb.h \
  /home/ijyothi/build-zynq/include/l4/sys/__kernel_object_impl.h \
  /home/ijyothi/build-zynq/include/arm/l4f/l4/sys/ipc.h \
  /home/ijyothi/build-zynq/include/l4/sys/ipc.h \
  /home/ijyothi/build-zynq/include/l4/sys/err.h \
  /home/ijyothi/build-zynq/include/arm/l4f/l4/sys/syscall_defs.h \
  /home/ijyothi/build-zynq/include/l4/sys/__typeinfo.h \
  /home/ijyothi/build-zynq/include/l4/sys/cxx/types \
  /home/ijyothi/build-zynq/include/l4/sys/cxx/ipc_basics \
  /home/ijyothi/build-zynq/include/l4/sys/cxx/capability.h \
  /home/ijyothi/build-zynq/include/arm/l4/sys/task.h \
  /home/ijyothi/build-zynq/include/l4/sys/task.h \
  /home/ijyothi/build-zynq/include/l4/sys/__task-arm.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/typeinfo \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/exception.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/c++config.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/os_defines.h \
  /home/ijyothi/build-zynq/include/uclibc/features.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/uClibc_config.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/l4-libc-symbols.h \
  /home/ijyothi/build-zynq/include/uclibc/sys/cdefs.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/cpu_defines.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/pstl/pstl_config.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/hash_bytes.h \
  /home/ijyothi/build-zynq/include/l4/sys/meta \
  /home/ijyothi/build-zynq/include/l4/sys/cxx/ipc_iface \
  /home/ijyothi/build-zynq/include/l4/sys/cxx/ipc_types \
    $(wildcard include/config/ALLOW_REFS) \
  /home/ijyothi/build-zynq/include/l4/sys/cxx/ipc_string \
  /home/ijyothi/build-zynq/include/l4/sys/cxx/ipc_array \
  /home/ijyothi/build-zynq/include/l4/re/protocols.h \
  /home/ijyothi/build-zynq/include/l4/sys/pager \
  /home/ijyothi/build-zynq/include/l4/sys/cxx/ipc_ret_array \
  /home/ijyothi/build-zynq/include/l4/re/consts \
  /home/ijyothi/build-zynq/include/l4/re/env.h \
  /home/ijyothi/build-zynq/include/l4/sys/kip.h \
    $(wildcard include/config/SYNC_TSC) \
    $(wildcard include/config/SYNC) \
  /home/ijyothi/build-zynq/include/arm/l4/sys/__kip-arch.h \
  /home/ijyothi/build-zynq/include/l4/sys/__kip-32bit.h \
  /home/ijyothi/build-zynq/include/l4/re/consts.h \
  /home/ijyothi/build-zynq/include/l4/re/dataspace \
  /home/ijyothi/build-zynq/include/l4/re/parent \
  /home/ijyothi/build-zynq/include/l4/re/mem_alloc \
  /home/ijyothi/build-zynq/include/l4/sys/factory \
  /home/ijyothi/build-zynq/include/l4/sys/factory.h \
  /home/ijyothi/build-zynq/include/l4/sys/cxx/ipc_varg \
  /home/ijyothi/build-zynq/include/l4/re/log \
  /home/ijyothi/build-zynq/include/l4/sys/vcon \
  /home/ijyothi/build-zynq/include/l4/sys/icu \
  /home/ijyothi/build-zynq/include/l4/sys/irq \
  /home/ijyothi/build-zynq/include/l4/sys/icu.h \
  /home/ijyothi/build-zynq/include/l4/sys/irq.h \
  /home/ijyothi/build-zynq/include/l4/sys/rcv_endpoint.h \
  /home/ijyothi/build-zynq/include/l4/sys/rcv_endpoint \
  /home/ijyothi/build-zynq/include/l4/sys/vcon.h \
  /home/ijyothi/build-zynq/include/l4/sys/iommu \
  /home/ijyothi/build-zynq/include/l4/re/error_helper \
  /home/ijyothi/build-zynq/include/l4/cxx/exceptions \
  /home/ijyothi/build-zynq/include/l4/cxx/l4types.h \
  /home/ijyothi/build-zynq/include/l4/cxx/basic_ostream \
  /home/ijyothi/build-zynq/include/l4/util/backtrace.h \
  /home/ijyothi/build-zynq/include/l4/cxx/type_traits \
  /home/ijyothi/build-zynq/include/l4/cxx/bits/type_traits.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/cassert \
  /home/ijyothi/build-zynq/include/uclibc/assert.h \
  /home/ijyothi/l4/pkg/io/io/server/src/dma_domain.h \
  /home/ijyothi/l4/pkg/io/io/server/src/resource.h \
  /home/ijyothi/build-zynq/include/l4/vbus/vbus_types.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/string \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/stringfwd.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/memoryfwd.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/char_traits.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/postypes.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/cwchar \
  /home/ijyothi/build-zynq/include/uclibc/wchar.h \
  /home/ijyothi/build-zynq/include/uclibc/stdio.h \
  /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/lib/gcc/arm-none-linux-gnueabihf/12.3.1/include/stdarg.h \
  /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/lib/gcc/arm-none-linux-gnueabihf/12.3.1/include/stddef.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/wchar.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/type_traits \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/cstdint \
  /home/ijyothi/build-zynq/include/uclibc/stdint.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/wordsize.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/allocator.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/c++allocator.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/new_allocator.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/new \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/functexcept.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/exception_defines.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/move.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/cpp_type_traits.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/localefwd.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/c++locale.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/clocale \
  /home/ijyothi/build-zynq/include/uclibc/locale.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/uClibc_locale.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/iosfwd \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/cctype \
  /home/ijyothi/build-zynq/include/uclibc/ctype.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/types.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/typesizes.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/uClibc_touplow.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/ostream_insert.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/cxxabi_forced.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/stl_iterator_base_types.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/stl_iterator_base_funcs.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/concept_check.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/debug/assertions.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/stl_iterator.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/ext/type_traits.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/ptr_traits.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/stl_function.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/backward/binders.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/ext/numeric_traits.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/stl_algobase.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/stl_pair.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/utility.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/debug/debug.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/predefined_ops.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/refwrap.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/invoke.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/range_access.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/initializer_list \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/basic_string.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/ext/alloc_traits.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/alloc_traits.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/stl_construct.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/string_view \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/functional_hash.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/string_view.tcc \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/ext/string_conversions.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/cstdlib \
  /home/ijyothi/build-zynq/include/uclibc/stdlib.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/waitflags.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/waitstatus.h \
  /home/ijyothi/build-zynq/include/uclibc/endian.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/endian.h \
  /home/ijyothi/build-zynq/include/uclibc/byteswap.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/byteswap.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/byteswap-common.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/byteswap-16.h \
  /home/ijyothi/build-zynq/include/uclibc/sys/types.h \
  /home/ijyothi/build-zynq/include/uclibc/time.h \
  /home/ijyothi/build-zynq/include/uclibc/sys/select.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/select.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/sigset.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/time.h \
  /home/ijyothi/build-zynq/include/uclibc/sys/sysmacros.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/pthreadtypes.h \
  /home/ijyothi/build-zynq/include/l4/sys/scheduler.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/sched.h \
  /home/ijyothi/build-zynq/include/uclibc/alloca.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/std_abs.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/cstdio \
  /home/ijyothi/build-zynq/include/uclibc/bits/uClibc_stdio.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/stdio_lim.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/cerrno \
  /home/ijyothi/build-zynq/include/uclibc/errno.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/errno.h \
  /home/ijyothi/build-zynq/include/uclibc/linux/errno.h \
  /home/ijyothi/build-zynq/include/uclibc/asm/errno.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/charconv.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/basic_string.tcc \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/vector \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/stl_uninitialized.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/stl_vector.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/stl_bvector.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/vector.tcc \
  /home/ijyothi/build-zynq/include/l4/re/util/cap_alloc \
  /home/ijyothi/build-zynq/include/l4/re/util/cap_alloc_impl.h \
  /home/ijyothi/build-zynq/include/l4/re/util/counting_cap_alloc \
  /home/ijyothi/build-zynq/include/l4/sys/task \
  /home/ijyothi/build-zynq/include/l4/sys/assert.h \
  /home/ijyothi/build-zynq/include/arm/l4/sys/thread.h \
  /home/ijyothi/build-zynq/include/l4/sys/thread.h \
  /home/ijyothi/build-zynq/include/l4/sys/smart_capability \
  /home/ijyothi/build-zynq/include/l4/re/util/unique_cap \
  /home/ijyothi/build-zynq/include/l4/sys/cxx/smart_capability_1x \
  /home/ijyothi/l4/pkg/io/io/server/src/res.h \
  /home/ijyothi/build-zynq/include/l4/re/dma_space \
  /home/ijyothi/l4/pkg/io/io/server/src/hw_device.h \
  /home/ijyothi/l4/pkg/io/io/server/src/device.h \
  /home/ijyothi/build-zynq/include/uclibc/fnmatch.h \
  /home/ijyothi/build-zynq/include/l4/cxx/minmax \
  /home/ijyothi/build-zynq/include/l4/cxx/string \
  /home/ijyothi/build-zynq/include/l4/cxx/bitfield \
  /home/ijyothi/build-zynq/include/l4/cxx/type_list \
  /home/ijyothi/build-zynq/include/l4/cxx/unique_ptr \
  /home/ijyothi/l4/pkg/io/io/server/src/debug.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/cstring \
  /home/ijyothi/build-zynq/include/uclibc/string.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/map \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/stl_tree.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/ext/aligned_buffer.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/node_handle.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/stl_map.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/tuple \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/uses_allocator.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/stl_multimap.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/erase_if.h \
  /home/ijyothi/l4/pkg/io/io/server/src/event_source.h \
  /home/ijyothi/build-zynq/include/l4/re/event \
  /home/ijyothi/build-zynq/include/l4/re/event.h \
  /home/ijyothi/l4/pkg/io/io/server/src/pm.h \
  /home/ijyothi/build-zynq/include/l4/cxx/hlist \
  /home/ijyothi/build-zynq/include/l4/cxx/bits/list_basics.h \
  /home/ijyothi/l4/pkg/io/io/server/src/type_matcher.h \
  /home/ijyothi/l4/pkg/io/io/server/src/hw_device_client.h \
  /home/ijyothi/build-zynq/include/l4/cxx/avl_map \
  /home/ijyothi/build-zynq/include/l4/cxx/std_alloc \
  /home/ijyothi/build-zynq/include/l4/cxx/std_ops \
  /home/ijyothi/build-zynq/include/l4/cxx/pair \
  /home/ijyothi/build-zynq/include/l4/cxx/avl_set \
  /home/ijyothi/build-zynq/include/l4/cxx/avl_tree \
  /home/ijyothi/build-zynq/include/l4/cxx/bits/bst.h \
  /home/ijyothi/build-zynq/include/l4/cxx/bits/bst_base.h \
  /home/ijyothi/build-zynq/include/l4/cxx/bits/bst_iter.h \
  /home/ijyothi/l4/pkg/io/io/server/src/main.h \

arm_dma_device.o: $(deps_arm_dma_device.o)

$(deps_arm_dma_device.o):
