L4DIR=/home/ijyothi/l4
OBJ_BASE=/home/ijyothi/build-zynq
OBJ_DIR=/home/ijyothi/build-zynq/pkg/uvmm/configs/dts
SRC_DIR=/home/ijyothi/l4/pkg/uvmm/configs/dts
PKGDIR=/home/ijyothi/l4/pkg/uvmm
PKGDIR_ABS=/home/ijyothi/l4/pkg/uvmm
PKGDIR_OBJ=/home/ijyothi/build-zynq/pkg/uvmm
MAKECONFLOCAL=/home/ijyothi/l4/pkg/uvmm/configs/dts/Makeconf.local
OSYSTEM=arm-l4f
SYSTEM=arm_armv7a-nofpu-l4f
ARCH=arm
CPU=armv7a
L4API=l4f
VARIANT=nofpu
vpath %.c /home/ijyothi/l4/pkg/uvmm/configs/dts
vpath %.cc /home/ijyothi/l4/pkg/uvmm/configs/dts
vpath %.cpp /home/ijyothi/l4/pkg/uvmm/configs/dts
vpath %.f /home/ijyothi/l4/pkg/uvmm/configs/dts
vpath %.F /home/ijyothi/l4/pkg/uvmm/configs/dts
vpath %.f90 /home/ijyothi/l4/pkg/uvmm/configs/dts
vpath %.F90 /home/ijyothi/l4/pkg/uvmm/configs/dts
vpath %.f95 /home/ijyothi/l4/pkg/uvmm/configs/dts
vpath %.F95 /home/ijyothi/l4/pkg/uvmm/configs/dts
vpath %.S /home/ijyothi/l4/pkg/uvmm/configs/dts
vpath %.y /home/ijyothi/l4/pkg/uvmm/configs/dts
vpath %.l /home/ijyothi/l4/pkg/uvmm/configs/dts
vpath %.ld /home/ijyothi/l4/pkg/uvmm/configs/dts
vpath %.dpe /home/ijyothi/l4/pkg/uvmm/configs/dts
vpath %.dts /home/ijyothi/l4/pkg/uvmm/configs/dts
.general.d: /home/ijyothi/l4/pkg/uvmm/configs/dts/Makefile
include $(OBJ_BASE)/include/config/auto.conf
include /home/ijyothi/l4/pkg/uvmm/configs/dts/Makefile
include $(L4DIR)/mk/lib.mk
