savedcmd_config/arm/pr-support.o := /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/bin/arm-none-linux-gnueabihf-gcc -c -MD -MP -MF config/arm/.pr-support.o.d -DL4SYS_USE_UTCB_WRAP=1 -DSYSTEM_arm_armv7a_nofpu_plain -DARCH_arm -DCPUTYPE_armv7a -DL4API_plain -D_GNU_SOURCE -DL4_MINIMAL_LIBC -DBID_VARIANT_FLAG_NOFPU -march=armv7-a+fp -mgeneral-regs-only -I/home/ijyothi/l4/pkg/l4re-core/libgcc_eh-pure/../libgcc/generated/arm/gcc -I/home/ijyothi/l4/pkg/l4re-core/libgcc_eh-pure/../libgcc/generated/arm/libgcc -I/home/ijyothi/l4/pkg/l4re-core/libgcc_eh-pure/../libgcc/contrib/gcc-12/include -I/home/ijyothi/l4/pkg/l4re-core/libgcc_eh-pure/../libgcc/contrib/gcc-12/gcc -I/home/ijyothi/l4/pkg/l4re-core/libgcc_eh-pure/../libgcc/contrib/gcc-12/libgcc -I/home/ijyothi/l4/pkg/l4re-core/libgcc_eh-pure/../libgcc/contrib/gcc-12/libgcc/config/arm -I/home/ijyothi/build-zynq/pkg/l4re-core/libgcc_eh-pure/lib/src -I/home/ijyothi/build-zynq/include/contrib/libgcc_eh -I/home/ijyothi/build-zynq/include/arm/plain -I/home/ijyothi/build-zynq/include/arm -I/home/ijyothi/build-zynq/include -I/home/ijyothi/build-zynq/include/contrib/libstdc++-v3 -nostdinc -I/home/ijyothi/build-zynq/include/uclibc -isystem /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/bin/../lib/gcc/arm-none-linux-gnueabihf/12.3.1/include -isystem /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/bin/../lib/gcc/arm-none-linux-gnueabihf/12.3.1/include-fixed -fno-omit-frame-pointer -fno-unwind-tables -g -O2 -fno-strict-aliasing -fno-common -std=gnu99 -marm -fmacro-prefix-map=/home/ijyothi/l4/= -fmacro-prefix-map=/home/ijyothi/build-zynq/= -march=armv7-a+fp -mgeneral-regs-only -fno-stack-protector -ffunction-sections -fdata-sections -O2 -g -O2 -DIN_GCC -DCROSS_DIRECTORY_STRUCTURE -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -DL4_LIBGCC_VERSION=12 -fPIC -g -DIN_LIBGCC2 -fbuilding-libgcc -fno-stack-protector -fvisibility=hidden -DHIDE_EXPORTS -fexceptions /home/ijyothi/l4/pkg/l4re-core/libgcc_eh-pure/../libgcc/contrib/gcc-12/libgcc/config/arm/pr-support.c -o config/arm/pr-support.o

source_config/arm/pr-support.o := /home/ijyothi/l4/pkg/l4re-core/libgcc_eh-pure/../libgcc/contrib/gcc-12/libgcc/config/arm/pr-support.c

deps_config/arm/pr-support.o := \
  /home/ijyothi/build-zynq/pkg/l4re-core/libgcc_eh-pure/lib/src/unwind.h \
  /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/lib/gcc/arm-none-linux-gnueabihf/12.3.1/include/unwind-arm-common.h \

config/arm/pr-support.o: $(deps_config/arm/pr-support.o)

$(deps_config/arm/pr-support.o):
