L4DIR=/home/ijyothi/l4
OBJ_BASE=/home/ijyothi/build-zynq
OBJ_DIR=/home/ijyothi/build-zynq/pkg/l4re-core/lua/examples/interpr
SRC_DIR=/home/ijyothi/l4/pkg/l4re-core/lua/examples/interpr
PKGDIR=/home/ijyothi/l4/pkg/l4re-core/lua
PKGDIR_ABS=/home/ijyothi/l4/pkg/l4re-core/lua
PKGDIR_OBJ=/home/ijyothi/build-zynq/pkg/l4re-core/lua
MAKECONFLOCAL=/home/ijyothi/l4/pkg/l4re-core/lua/examples/interpr/Makeconf.local
OSYSTEM=arm-l4f
SYSTEM=arm_armv7a-std-l4f
ARCH=arm
CPU=armv7a
L4API=l4f
VARIANT=std
vpath %.c /home/ijyothi/l4/pkg/l4re-core/lua/examples/interpr
vpath %.cc /home/ijyothi/l4/pkg/l4re-core/lua/examples/interpr
vpath %.cpp /home/ijyothi/l4/pkg/l4re-core/lua/examples/interpr
vpath %.f /home/ijyothi/l4/pkg/l4re-core/lua/examples/interpr
vpath %.F /home/ijyothi/l4/pkg/l4re-core/lua/examples/interpr
vpath %.f90 /home/ijyothi/l4/pkg/l4re-core/lua/examples/interpr
vpath %.F90 /home/ijyothi/l4/pkg/l4re-core/lua/examples/interpr
vpath %.f95 /home/ijyothi/l4/pkg/l4re-core/lua/examples/interpr
vpath %.F95 /home/ijyothi/l4/pkg/l4re-core/lua/examples/interpr
vpath %.S /home/ijyothi/l4/pkg/l4re-core/lua/examples/interpr
vpath %.y /home/ijyothi/l4/pkg/l4re-core/lua/examples/interpr
vpath %.l /home/ijyothi/l4/pkg/l4re-core/lua/examples/interpr
vpath %.ld /home/ijyothi/l4/pkg/l4re-core/lua/examples/interpr
vpath %.dpe /home/ijyothi/l4/pkg/l4re-core/lua/examples/interpr
vpath %.dts /home/ijyothi/l4/pkg/l4re-core/lua/examples/interpr
.general.d: /home/ijyothi/l4/pkg/l4re-core/lua/examples/interpr/Makefile
include $(OBJ_BASE)/include/config/auto.conf
include /home/ijyothi/l4/pkg/l4re-core/lua/examples/interpr/Makefile
include $(L4DIR)/mk/prog.mk
