savedcmd_vfs.s.o := /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/bin/arm-none-linux-gnueabihf-g++ -c -MD -MP -MF ./.vfs.s.o.d -DNOT_IN_libc -DIS_IN_rtld -DLDSO_ELFINTERP=\"arm/elfinterp.c\" -include libc-symbols.h -DUCLIBC_LDSO=\"libld-l4.so\" -DUCLIBC_RUNTIME_PREFIX=\"/\" -D__LDSO_SEARCH_INTERP_PATH__=1 -DIS_IN_rtld -D__LIBDL_SHARED__ -DSHARED -D__UCLIBC_HAS_SSP__=1 -DSYSTEM_arm_armv7a_std_l4f -DARCH_arm -DCPUTYPE_armv7a -DL4API_l4f -D_GNU_SOURCE -DUSE_TLS=1 -DUSE___THREAD=1 -march=armv7-a+fp -I/home/ijyothi/build-zynq/include/uclibc -I/home/ijyothi/l4/pkg/l4re-core/ldso/../uclibc/lib/contrib/uclibc/ldso/ldso/arm -I/home/ijyothi/l4/pkg/l4re-core/ldso/ldso -I/home/ijyothi/l4/pkg/l4re-core/ldso/../uclibc/lib/contrib/uclibc/ldso/include -I/home/ijyothi/l4/pkg/l4re-core/ldso/../uclibc/lib/libpthread/src -I/home/ijyothi/l4/pkg/l4re-core/ldso/../uclibc/lib/libpthread/src/sysdeps/arm -I/home/ijyothi/build-zynq/include/contrib/libgcc_eh -I/home/ijyothi/build-zynq/include/arm/l4f -I/home/ijyothi/build-zynq/include/arm -I/home/ijyothi/build-zynq/include -I/home/ijyothi/build-zynq/include/contrib/libstdc++-v3 -nostdinc -I/home/ijyothi/build-zynq/include/uclibc -isystem /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/bin/../lib/gcc/arm-none-linux-gnueabihf/12.3.1/include -isystem /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/bin/../lib/gcc/arm-none-linux-gnueabihf/12.3.1/include-fixed -fno-unwind-tables -g -O2 -Wextra -Wdouble-promotion -Wfloat-conversion -Wfloat-equal -Wlogical-op -Wall -Wmissing-declarations -Wno-noexcept-type -Wno-psabi -fno-common -march=armv7-a+fp -marm -fmacro-prefix-map=/home/ijyothi/l4/= -fmacro-prefix-map=/home/ijyothi/build-zynq/= -DL4_GCC_HAS_ATOMICS -fno-stack-protector -fuse-cxa-atexit -ffunction-sections -fdata-sections -DL4_NO_RTTI -fno-rtti -fno-exceptions -fvisibility=hidden -fno-threadsafe-statics -O3 -fPIC -U__PIC__ -D__PIC__=1 /home/ijyothi/l4/pkg/l4re-core/ldso/ldso/vfs.cc -o vfs.s.o

source_vfs.s.o := /home/ijyothi/l4/pkg/l4re-core/ldso/ldso/vfs.cc

deps_vfs.s.o := \
  /home/ijyothi/build-zynq/include/uclibc/libc-symbols.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/uClibc_arch_features.h \
  /home/ijyothi/build-zynq/include/l4/crtn/initpriorities.h \
  /home/ijyothi/build-zynq/include/l4/util/util.h \
  /home/ijyothi/build-zynq/include/l4/sys/types.h \
  /home/ijyothi/build-zynq/include/arm/l4/sys/l4int.h \
  /home/ijyothi/build-zynq/include/l4/sys/l4int.h \
  /home/ijyothi/build-zynq/include/l4/sys/compiler.h \
  /home/ijyothi/build-zynq/include/arm/l4/sys/linkage.h \
  /home/ijyothi/build-zynq/include/arm/l4/sys/consts.h \
  /home/ijyothi/build-zynq/include/l4/sys/consts.h \
  /home/ijyothi/build-zynq/include/l4/sys/__l4_fpage.h \
  /home/ijyothi/build-zynq/include/l4/sys/__timeout.h \
  /home/ijyothi/build-zynq/include/arm/l4f/l4/sys/ipc.h \
  /home/ijyothi/build-zynq/include/l4/sys/ipc.h \
  /home/ijyothi/build-zynq/include/arm/l4/sys/utcb.h \
  /home/ijyothi/build-zynq/include/l4/sys/utcb.h \
  /home/ijyothi/build-zynq/include/l4/sys/err.h \
  /home/ijyothi/build-zynq/include/arm/l4f/l4/sys/syscall_defs.h \
  /home/ijyothi/build-zynq/include/l4/re/env \
  /home/ijyothi/build-zynq/include/l4/re/rm \
  /home/ijyothi/build-zynq/include/l4/sys/capability \
  /home/ijyothi/build-zynq/include/l4/sys/kobject \
  /home/ijyothi/build-zynq/include/l4/sys/kernel_object.h \
  /home/ijyothi/build-zynq/include/l4/sys/__kernel_object_impl.h \
  /home/ijyothi/build-zynq/include/l4/sys/__typeinfo.h \
  /home/ijyothi/build-zynq/include/l4/sys/cxx/types \
  /home/ijyothi/build-zynq/include/l4/sys/cxx/ipc_basics \
  /home/ijyothi/build-zynq/include/l4/sys/cxx/capability.h \
  /home/ijyothi/build-zynq/include/arm/l4/sys/task.h \
  /home/ijyothi/build-zynq/include/l4/sys/task.h \
  /home/ijyothi/build-zynq/include/l4/sys/__task-arm.h \
  /home/ijyothi/build-zynq/include/l4/sys/meta \
  /home/ijyothi/build-zynq/include/l4/sys/cxx/ipc_iface \
  /home/ijyothi/build-zynq/include/l4/sys/cxx/ipc_types \
    $(wildcard include/config/ALLOW_REFS) \
  /home/ijyothi/build-zynq/include/l4/sys/cxx/ipc_string \
  /home/ijyothi/build-zynq/include/l4/sys/cxx/ipc_array \
  /home/ijyothi/build-zynq/include/l4/re/protocols.h \
  /home/ijyothi/build-zynq/include/l4/sys/pager \
  /home/ijyothi/build-zynq/include/l4/sys/cxx/ipc_ret_array \
  /home/ijyothi/build-zynq/include/l4/re/consts \
  /home/ijyothi/build-zynq/include/l4/re/env.h \
  /home/ijyothi/build-zynq/include/l4/sys/kip.h \
    $(wildcard include/config/SYNC_TSC) \
    $(wildcard include/config/SYNC) \
  /home/ijyothi/build-zynq/include/arm/l4/sys/__kip-arch.h \
  /home/ijyothi/build-zynq/include/l4/sys/__kip-32bit.h \
  /home/ijyothi/build-zynq/include/l4/re/consts.h \
  /home/ijyothi/build-zynq/include/l4/re/dataspace \
  /home/ijyothi/build-zynq/include/l4/re/parent \
  /home/ijyothi/build-zynq/include/l4/re/mem_alloc \
  /home/ijyothi/build-zynq/include/l4/sys/factory \
  /home/ijyothi/build-zynq/include/l4/sys/factory.h \
  /home/ijyothi/build-zynq/include/l4/sys/cxx/ipc_varg \
  /home/ijyothi/build-zynq/include/l4/re/log \
  /home/ijyothi/build-zynq/include/l4/sys/vcon \
  /home/ijyothi/build-zynq/include/l4/sys/icu \
  /home/ijyothi/build-zynq/include/l4/sys/irq \
  /home/ijyothi/build-zynq/include/l4/sys/icu.h \
  /home/ijyothi/build-zynq/include/l4/sys/irq.h \
  /home/ijyothi/build-zynq/include/l4/sys/rcv_endpoint.h \
  /home/ijyothi/build-zynq/include/l4/sys/rcv_endpoint \
  /home/ijyothi/build-zynq/include/l4/sys/vcon.h \
  /home/ijyothi/build-zynq/include/l4/re/util/bitmap_cap_alloc \
  /home/ijyothi/build-zynq/include/l4/re/util/item_alloc \
  /home/ijyothi/build-zynq/include/l4/cxx/bitmap \
  /home/ijyothi/build-zynq/include/l4/re/cap_alloc \
  /home/ijyothi/build-zynq/include/l4/sys/task \
  /home/ijyothi/build-zynq/include/l4/sys/smart_capability \
  /home/ijyothi/build-zynq/include/l4/cxx/type_traits \
  /home/ijyothi/build-zynq/include/l4/cxx/bits/type_traits.h \
  /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/lib/gcc/arm-none-linux-gnueabihf/12.3.1/include/stddef.h \
  /home/ijyothi/build-zynq/include/uclibc/dlfcn.h \
  /home/ijyothi/build-zynq/include/uclibc/features.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/uClibc_config.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/l4-libc-symbols.h \
  /home/ijyothi/build-zynq/include/uclibc/sys/cdefs.h \
  /home/ijyothi/build-zynq/include/uclibc/libc-internal.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/dlfcn.h \
  /home/ijyothi/build-zynq/include/l4/re/impl/dataspace_impl.h \
  /home/ijyothi/build-zynq/include/l4/sys/cxx/ipc_client \
  /home/ijyothi/build-zynq/include/l4/sys/cxx/consts \
  /home/ijyothi/build-zynq/include/l4/re/impl/rm_impl.h \
  /home/ijyothi/build-zynq/include/l4/re/impl/namespace_impl.h \
  /home/ijyothi/build-zynq/include/l4/re/namespace \
  /home/ijyothi/build-zynq/include/l4/sys/assert.h \
  /home/ijyothi/build-zynq/include/arm/l4/sys/thread.h \
  /home/ijyothi/build-zynq/include/l4/sys/thread.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/cstring \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/c++config.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/os_defines.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/bits/cpu_defines.h \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/pstl/pstl_config.h \
  /home/ijyothi/build-zynq/include/uclibc/string.h \
  /home/ijyothi/build-zynq/include/l4/re/impl/mem_alloc_impl.h \
  /home/ijyothi/build-zynq/include/l4/re/mem_alloc-sys.h \
  /home/ijyothi/build-zynq/include/l4/re/error_helper \
  /home/ijyothi/build-zynq/include/l4/cxx/exceptions \
  /home/ijyothi/build-zynq/include/l4/cxx/l4types.h \
  /home/ijyothi/build-zynq/include/l4/cxx/basic_ostream \
  /home/ijyothi/build-zynq/include/l4/util/backtrace.h \
  /home/ijyothi/build-zynq/include/l4/l4re_vfs/impl/ns_fs_impl.h \
  /home/ijyothi/build-zynq/include/l4/l4re_vfs/impl/ns_fs.h \
  /home/ijyothi/build-zynq/include/l4/l4re_vfs/backend \
  /home/ijyothi/build-zynq/include/l4/l4re_vfs/vfs.h \
  /home/ijyothi/build-zynq/include/uclibc/unistd.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/posix_opt.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/uClibc_posix_opt.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/environments.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/wordsize.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/types.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/kernel_types.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/typesizes.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/confname.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/getopt.h \
  /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/lib/gcc/arm-none-linux-gnueabihf/12.3.1/include/stdarg.h \
  /home/ijyothi/build-zynq/include/uclibc/fcntl.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/fcntl.h \
  /home/ijyothi/build-zynq/include/uclibc/sys/types.h \
  /home/ijyothi/build-zynq/include/uclibc/time.h \
  /home/ijyothi/build-zynq/include/uclibc/endian.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/endian.h \
  /home/ijyothi/build-zynq/include/uclibc/stdint.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/wchar.h \
  /home/ijyothi/build-zynq/include/uclibc/byteswap.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/byteswap.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/byteswap-common.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/byteswap-16.h \
  /home/ijyothi/build-zynq/include/uclibc/sys/select.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/select.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/sigset.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/time.h \
  /home/ijyothi/build-zynq/include/uclibc/sys/sysmacros.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/pthreadtypes.h \
  /home/ijyothi/build-zynq/include/l4/sys/scheduler.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/sched.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/uio.h \
  /home/ijyothi/build-zynq/include/uclibc/sys/stat.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/stat.h \
  /home/ijyothi/build-zynq/include/uclibc/sys/mman.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/mman.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/mman-common.h \
  /home/ijyothi/build-zynq/include/uclibc/sys/socket.h \
  /home/ijyothi/build-zynq/include/uclibc/sys/uio.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/socket.h \
  /home/ijyothi/build-zynq/include/uclibc/limits.h \
  /home/ijyothi/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-linux-gnueabihf/lib/gcc/arm-none-linux-gnueabihf/12.3.1/include-fixed/limits.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/posix1_lim.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/local_lim.h \
  /home/ijyothi/build-zynq/include/uclibc/linux/limits.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/uClibc_local_lim.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/posix2_lim.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/xopen_lim.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/stdio_lim.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/socket_type.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/sockaddr.h \
  /home/ijyothi/build-zynq/include/uclibc/asm/socket.h \
  /home/ijyothi/build-zynq/include/uclibc/utime.h \
  /home/ijyothi/build-zynq/include/uclibc/errno.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/errno.h \
  /home/ijyothi/build-zynq/include/uclibc/linux/errno.h \
  /home/ijyothi/build-zynq/include/uclibc/asm/errno.h \
  /home/ijyothi/build-zynq/include/l4/cxx/pair \
  /home/ijyothi/build-zynq/include/l4/cxx/ref_ptr \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/cstddef \
  /home/ijyothi/build-zynq/include/l4/re/unique_cap \
  /home/ijyothi/build-zynq/include/l4/sys/cxx/smart_capability_1x \
  /home/ijyothi/build-zynq/include/l4/re/util/env_ns \
  /home/ijyothi/build-zynq/include/l4/re/util/cap_alloc \
  /home/ijyothi/build-zynq/include/l4/re/util/cap_alloc_impl.h \
  /home/ijyothi/build-zynq/include/l4/re/util/counting_cap_alloc \
  /home/ijyothi/build-zynq/include/uclibc/dirent.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/dirent.h \
  /home/ijyothi/build-zynq/include/l4/l4re_vfs/impl/ro_file_impl.h \
  /home/ijyothi/build-zynq/include/l4/l4re_vfs/impl/ro_file.h \
  /home/ijyothi/build-zynq/include/uclibc/sys/ioctl.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/ioctls.h \
  /home/ijyothi/build-zynq/include/uclibc/asm/ioctls.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/ioctl-types.h \
  /home/ijyothi/build-zynq/include/uclibc/sys/ttydefaults.h \
  /home/ijyothi/build-zynq/include/l4/l4re_vfs/impl/fd_store_impl.h \
  /home/ijyothi/build-zynq/include/l4/l4re_vfs/impl/fd_store.h \
  /home/ijyothi/build-zynq/include/l4/l4re_vfs/impl/vcon_stream_impl.h \
  /home/ijyothi/build-zynq/include/l4/cxx/minmax \
  /home/ijyothi/build-zynq/include/l4/l4re_vfs/impl/vcon_stream.h \
  /home/ijyothi/build-zynq/include/l4/sys/semaphore \
  /home/ijyothi/build-zynq/include/l4/sys/semaphore.h \
  /home/ijyothi/build-zynq/include/uclibc/termios.h \
  /home/ijyothi/build-zynq/include/uclibc/bits/termios.h \
  /home/ijyothi/build-zynq/include/l4/l4re_vfs/impl/vfs_impl.h \
  /home/ijyothi/build-zynq/include/l4/cxx/hlist \
  /home/ijyothi/build-zynq/include/l4/cxx/bits/list_basics.h \
  /home/ijyothi/build-zynq/include/l4/cxx/std_alloc \
  /home/ijyothi/build-zynq/include/l4/re/shared_cap \
  /home/ijyothi/build-zynq/include/contrib/libstdc++-v3/cstdarg \
  /home/ijyothi/build-zynq/include/l4/l4re_vfs/impl/default_ops_impl.h \
  /home/ijyothi/build-zynq/include/l4/cxx/static_container \

vfs.s.o: $(deps_vfs.s.o)

$(deps_vfs.s.o):
